### ISSUE TITLE
Access to console in game?

### ISSUE THREAD

**Issue by inexion** [Nimdy/Dedicated_Valheim_Server_Script#10]
Need a way to either access the console and type commands, or add individual users to the admin list so they can run commands in game

**Comment by Nimdy** [comment]
Not a Script Issue.

Press F5

**Comment by inexion** [comment]
F5 only opens the console, this doesn't grant admin access to anyone though if the server is running on a droplet in Digital Ocean

**Comment by Nimdy** [comment]
oh I see.... I read that wrong this morning... Sorry.

Go to /home/steam/.config/unity3d/IronGate/Valheim/
edit adminlist.txt
add the steam64id of the user you wish to be a admin
save file.

Any new admins must be added line by line.
