### ISSUE TITLE
Restore World

### ISSUE THREAD

**Issue by SerrikVorrik** [Nimdy/Dedicated_Valheim_Server_Script#100]
no option to backup a menu without doing control+c to escape which closes the menu.

**Comment by Nimdy** [comment]
huh?

**Comment by SerrikVorrik** [comment]
Sorry no option to back out of the restore menu if you select the option from the option menu by mistake.

**Comment by BillChirico** [comment]
> Sorry no option to back out of the restore menu if you select the option from the option menu by mistake.
> 
> ![noback](https://user-images.githubusercontent.com/53182168/109570047-a9fcaa00-7aa6-11eb-89af-77fef4249e1d.PNG)
> 
> 

How did you get to that menu?

**Comment by Nimdy** [comment]
Update your menu. It's been added. 😁

**Comment by SerrikVorrik** [comment]
Please merge into branch.

**Comment by Nimdy** [comment]
option added and message added to inform user the next section after selecting a file adds cancel options.
