### ISSUE TITLE
[Issue] CWorkThreadPool error when applying / checking for server update

### ISSUE THREAD

**Issue by VP-EN** [Nimdy/Dedicated_Valheim_Server_Script#106]
Hey again :)

Got another "bug". Not sure if it does anything harmful though.
Whenever I check for a new server update, and / or apply it, this error comes up:
`CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 1 items discarded.`

Right now I can reproduce it, by doing the following:
1. Open menu.sh (`./menu.sh`)
2. Entering sudo password
3. Choosing `2) Server Admin Tools`
4. Choosing `7) Check and Apply Valheim Server Update`
5. Entering `y` in the confirmation prompt
6. Getting the CWorkThreadPool error.

Full log (after the update applied):
```
Downloading Official Valheim Repo Log Data for comparison only
Redirecting stderr to '/root/.steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x61) downloading, progress: 0.00 (0 / 1051599543)
 Update state (0x61) downloading, progress: 1.60 (16777216 / 1051599543)
 Update state (0x61) downloading, progress: 20.33 (213821304 / 1051599543)
 Update state (0x61) downloading, progress: 47.39 (498347207 / 1051599543)
 Update state (0x61) downloading, progress: 74.62 (784674943 / 1051599543)
 Update state (0x61) downloading, progress: 99.44 (1045679703 / 1051599543)
Success! App '896660' fully installed.
CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 1 items discarded.
Official Valheim-: "buildid""6315977"
Local Valheim Ver: "buildid""6315977"
No new Updates found
Cleaning up TEMP FILES
```

**Comment by Nimdy** [comment]
i believe this to be the cache file steam creates... I will test when I get home... because I guess there was another server update today.

I will be home in a hour.

**Comment by Nimdy** [comment]
nope. Everything is working as required.

Just try rebooting your server.

**Comment by VP-EN** [comment]
Yeah, rebooting seemed to do the trick. Not sure why I didn't try that first 👍
