### ISSUE TITLE
1.7.8 - Can't update and ill-timed error message

### ISSUE THREAD

**Issue by didyouexpectthat** [Nimdy/Dedicated_Valheim_Server_Script#109]
2 complaints:
When I push 1 to check for updates, it just takes me back to the  menu. 
The problem is that something strange happened to git (I am only using your script to update itself). 

**Problem 1**
Can't update successfully after upgrading to 1.7.8.
**Problem 2**
The error happens so damn fast and then you clear the results so nobody sees the output from the previous error. 
```
╔═════════════════════════════════════════╗
║~~~-ZeroBandwidths Easy Valheim Menu-~~~~║
╠═════════════════════════════════════════╝
║ Welcome Viking!
║ open to improvements
║ Beware Loki hides within this script
╚ Version 1.7.8-Loki
----------Check for Script Updates---------
- 1) Check for Menu Script Updates
-----------Valheim Server Commands---------
- 2) Server Admin Tools
- 3) Tech Support Tools
- 4) Install Valheim Server
-----------------Mods Menu-----------------
- 5) Coming Soon
-------------------------------------------
 0) Exit
-------------------------------------------
Choose an option: + read a
1
+ case $a in
+ script_check_update
+ git fetch
fatal: Not a git repository (or any of the parent directories): .git
++ git diff --name-only '' menu.sh
error: Could not access ''
+ '[' -n '' ']'
+ echo 'Oh for Loki sakes! No updates to be had... back to choring! '
Oh for Loki sakes! No updates to be had... back to choring!
+ menu
+ clear
```

**Comment by didyouexpectthat** [comment]
I can fix the git myself, but I just wanted to report the problem before I blow it all away and get it up to 1.8.

**Comment by Nimdy** [comment]
remove the dedicate folder
go back to /opt
rm -Rf Dedica(press tab)
press enter
git clone https://github.com/Nimdy/Dedicated_Valheim_Server_Script.git
