### ISSUE TITLE
Servername should be set in quotation marks 

### ISSUE THREAD

**Issue by Pendora2017** [Nimdy/Dedicated_Valheim_Server_Script#11]
Hi there and thank you for this nice script!

I installed a server with the help of the script but had to find out that if the name contains spaces, not the entire name is displayed as the server name. So i edited the "start_valheim.sh" manually and set the name in quotations marks. That worked.

Before: my Home results in Servername "my"
After: 'my Home' results in Servername "my Home"

**Comment by xaviablaza** [comment]
728686f16b90d33578e0ea6d76093a2a74148419 closes this issue
