### ISSUE TITLE
Display Connected Players Issue

### ISSUE THREAD

**Issue by Choguy** [Nimdy/Dedicated_Valheim_Server_Script#110]
When using the Menu and accessing Connected Players History, it returns blank. 

I know there have been several users connected. 

Totally not a big deal for me, but figured I would let you know. Plus it could definitely be a user problem. lol.

**Comment by cheeseandcereal** [comment]
This is due to syslog rotation. I added a PR to search all syslogs to fix this issue if maintainers want to merge it.

**Comment by Nimdy** [comment]
thanks we will look at it. :)

**Comment by Nimdy** [comment]
I will test and add this on the beta branch today... If everything works, I will add it but most people will not use this. The only the advance users normally... This is script is designed for somebody who doesnt know Linux at all. I am attempting to make this the gateway drug for them to become fans of Linux and start using Linux more and more. :) 

I will let you know
