### ISSUE TITLE
Why do we need to remove the private IP address on DO?

### ISSUE THREAD

**Issue by marcopiraccini** [Nimdy/Dedicated_Valheim_Server_Script#114]
I know, it's useless, but should be harmless.
Or there is a reason I don't see?

**Comment by Nimdy** [comment]
you dont need to  but if it give you issues, then nuke it.  You can setup the tcp/udp ports from the firewall droplet tab.

Sometimes... folks just have issues... idky.... but that is the fail safe.  This was a huge issue with ARK and RUST

**Comment by Nimdy** [comment]
something to do with the socket binding to the private IP address and not the public...

**Comment by marcopiraccini** [comment]
I tried quickly and it seems to work also if I leave the internal network IP. Will do more tests later.
