### ISSUE TITLE
1.8- Script assumes path

### ISSUE THREAD

**Issue by didyouexpectthat** [Nimdy/Dedicated_Valheim_Server_Script#117]
```
╔═════════════════════════════════════════╗
║~~~-ZeroBandwidths Easy Valheim Menu-~~~~║
╠═════════════════════════════════════════╝
║ Welcome Viking!
║ open to improvements
║ Beware Loki hides within this script
╚ Version 1.8-Loki
----------Check for Script Updates---------
- 1) Check for Menu Script Updates
-----------Valheim Server Commands---------
- 2) Server Admin Tools
- 3) Tech Support Tools
- 4) Install Valheim Server
-----------------Mods Menu-----------------
- 5) Coming Soon
-------------------------------------------
 0) Exit
-------------------------------------------
Choose an option: 1
BY THORS HAMMER take a peek inside Valhalla!!
Already up-to-date.
Saved working directory and index state WIP on main: 268ad7f Update README.md
HEAD is now at 268ad7f Update README.md
Already on 'main'
Your branch is up-to-date with 'origin/main'.
Already up-to-date.
 Updating
menu.sh: line 141: cd: /opt/Dedicated_Valheim_server_Script/: No such file or directory
menu.sh: line 143: exec: menu.sh: not found
```

I `git clone` to /opt/valheim instead. 
https://github.com/Nimdy/Dedicated_Valheim_Server_Script/blob/268ad7f91829ac5036d4a06be5002a9f74e15d88/menu.sh#L141
Should use $SCRIPTPATH instead.

**Comment by Nimdy** [comment]
yeah... I still need to discuss this more... Advance users will dump this where ever this wish.... I am trying to protect non-linux users from jacking up their Linux boxes.

While there is no hard in the placement of the git clone... I just wonder, what damage... non-linux could do, while inside... root's home... the steam accounts home... whatever else they magically are in the current folder structure...

**Comment by didyouexpectthat** [comment]
Non-Linux users copy/paste commands from websites into terminal windows.  By ensuring your instructions for those users are always clear from a copy/paste standpoint, they shouldn't be deviating by cloning the repo into /root or somewhere else. 

To make this more simple for them, you could lessen the steps for non-Linux users to a curl script, something like 
`curl https://raw.githubusercontent.com/Nimdy/Dedicated_Valheim_Server_Script/main/install.sh | bash -` 
It could perform the tasks to setup the script in that manner.

**Comment by Nimdy** [comment]
thanks.
I will try that.

You would be surprise on some of the issues I help people with... its mind blowing... I was helping one person and ended up following them into Narnia....   looking through history, I could even figure out how they got into the situation they were in.

I love puzzles... but damn 4 hours of TSing with them.... ended up just building them server for them myself with their account info and launching the menu system... zero issues.

**Comment by Nimdy** [comment]
removed the line as its not needed. 

Thanks
