### ISSUE TITLE
Please add a install dialog for the option "-public 1"

### ISSUE THREAD

**Issue by Pendora2017** [Nimdy/Dedicated_Valheim_Server_Script#12]
It's me again ;)

Perhaps you can add a dialog that asks if the server should be public.

I've just done more than 2 hours of error analysis why my server is not in the official server list 😃

**Comment by Nimdy** [comment]
this is still hit or miss. IronGate stated it did not work.

I have servers show up in the official server list and none of my configs have -public 1.

Once IronGate and Steam server browser is tweaked, I will add it the real fix.

Noted though.  Thank you.

**Comment by Nimdy** [comment]
That parameter was deprecated from day one and is removed by now. - beko

It is no longer used.
