### ISSUE TITLE
Automatic backups

### ISSUE THREAD

**Issue by dzanaga** [Nimdy/Dedicated_Valheim_Server_Script#120]
Thanks a lot for this awesome script!

This is a feature request, not an issue.
I was planning on copying the backup function to a separate script, remove the confirmations and just manually add a cron job to run it every day at 7 AM. I am not that experienced with bash, and was wondering if this is something that could be automated directly in the script and activated from there?

**Comment by Nimdy** [comment]
There is a plan and it will be conducted via cron job.  This option will be added and you can see what the current cron job is and edit it, if needed.  (add/create/modify)

**Comment by Nimdy** [comment]
https://github.com/Nimdy/Dedicated_Valheim_Server_Script/wiki/How-to-backup-Valheim-Server-World-Data-in-Ubuntu

I feel this is the best way.

I will add this to the script for people to turn on hourly backups

**Comment by niklasfrick** [comment]
I put together a script doing just that and it works fine for me: https://github.com/niklasfrick/valheim-server-backup

**Comment by dzanaga** [comment]
@niklasfrick looks great, thanks!
