### ISSUE TITLE
Add Admin server 

### ISSUE THREAD

**Issue by deevor** [Nimdy/Dedicated_Valheim_Server_Script#121]
Hi, i would like add a admin server but doesnt work.

I have adding my steamID64 obtain on https://steamidfinder.com in 
/home/steam/.config/unity3d/IronGate/Valheim/adminlist.txt 
Have u a another method ? maybe adding to menu :P

Thanks for ur help and ur work !

**Comment by VP-EN** [comment]
You'll need to gather your ID from inside the game.. I think it's Valheim-specific.

You can press "F2" ingame, and the ID will be on the right from your player-name.

Example:
![Example](https://i.imgur.com/pIqXCC4.png)

**Comment by deevor** [comment]
Thanks for ur help,  ID in game its a same that steamid(dec). 
I have adding ids of my mates for testing, command admin doesnt work either.
cat adminlist.txt shows me the steam id yet.

For u admin console working ?

**Comment by VP-EN** [comment]
Yeah, it works just fine. And you're right, it's the exact same ID as `steamID64 (Dec)`.
From my `adminlist.txt`
```
// List admin players ID  ONE per line
76561212341234569
```
(not my real ID)

**Comment by deevor** [comment]
ok, i understood it's possible to ban / kick but spawn item or freefly ... are not possible on dedicated server.
I was admin but I trying to spawn items. 

Showing here:
https://www.reddit.com/r/valheim/comments/lg9sfs/cant_use_imacheater_on_dedicated_server/

**Comment by VP-EN** [comment]
Yeah, no, you can't use those commands on a dedicated server. Only in singleplayer, as far as I understand.

For those kind of features, you might want to look into installing [BepInEx](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/) on your server, and finding mods that suits your needs. 

But for this, I'm pretty sure Nimdy doesn't offer any support 👍

**Comment by Nimdy** [comment]
https://www.youtube.com/watch?v=MUDKpW9It90

I made a video just for this
