### ISSUE TITLE
[Feature Request] Multiple Server Installs

### ISSUE THREAD

**Issue by VP-EN** [Nimdy/Dedicated_Valheim_Server_Script#122]
Hey again Nimdy, 
It would be nice with some support for installing different Valheim servers, on the same server. Not sure if this is out-of-the-scope for the purpose of the `menu.sh` script.

Maybe instead of using the default username `steam` it could be defined by `$USERNAME` or something like that.

I could probably just edit the script on my own, or setup the 2nd server manually.. 
But it would be nice to have either 2 separate  scripts for either server, or just one `menu.sh` script for managing both servers. I mainly use the `menu.sh` for checking for updates and backup'ing the server.

Also, thanks for the all the work so far 😄 !!

**Comment by ramonsaraiva** [comment]
I'd suggest to maybe have a Dockerfile and instantiate valheim servers into containers - so you can use the same host with different namespaces, basically.

**Comment by Nimdy** [comment]
this can be done...

no need to change the steam... that is just going to cause drama....

I would find valheimserver and replace with valheimserver2, where ever it is found in the script...

No promises it will work your first try but others have already done it.

**Comment by VP-EN** [comment]
Alright, I'll look into it. Thanks 👍
