### ISSUE TITLE
Local ip is the only way to join the server :(

### ISSUE THREAD

**Issue by BrainOffMeta** [Nimdy/Dedicated_Valheim_Server_Script#123]
I use an old laptop running Lubuntu for this, and I only can join the server by using it's local ip followed by the port 2456...
Until there it's all good, but how can I allow my friends to join the server too from another router ?
Did I miss something ?

Thanks again for your amazing work !

**Comment by VP-EN** [comment]
Did you forward your ports in your router? Assuming you're running this from your local network.
A lot of guides can be found for a lot of router models [here](https://portforward.com/)

**Comment by BrainOffMeta** [comment]
Yep I did forward the ports in udp/tcp in my router, i'll try to open them on lubuntu too ! I guess this is my mistake
I'll be back to up if it works
Thank you for your support :D

**Comment by BrainOffMeta** [comment]
Okay so I typed those commands, the ports are open on both Lubuntu and the router, but it doesn't work :/
I'm new to this, can you give me an exemple of the ip:port I should enter to join the server please ?
I tried 88.X.178.33:2456 and 88.X.178.33:2457, and my Lubuntu's IP is 192.168.0.49

**Comment by VP-EN** [comment]
Yeah it should be `88.X.178.49:2456`. If you enter your IP on [this webpage](https://geekstrom.de/valheim/check/), what does it say?

**Comment by BrainOffMeta** [comment]
With and without :2456 it says "No :("

**Comment by VP-EN** [comment]
Probably something off on your port forwarding rules then. Can you attach some kind of screenshot of your portforwarding setup?

**Comment by BrainOffMeta** [comment]
![screen](https://user-images.githubusercontent.com/72817214/110032073-075b5a00-7d38-11eb-9150-24906d945d2d.jpg)

**Comment by BrainOffMeta** [comment]
the ufw commands returned "rule already exists" for udp and tcp

**Comment by VP-EN** [comment]
Oh shit, I meant from your router page :)

**Comment by BrainOffMeta** [comment]
Oh, here it is xD
![image](https://user-images.githubusercontent.com/72817214/110032507-818bde80-7d38-11eb-92ef-1176479a3bf7.png)

**Comment by VP-EN** [comment]
Why is your port 22456? It's supposed to be `2456` in "`Port de début`" and `2458` in "`Port de fin`" in both UDP and TCP :)

**Comment by BrainOffMeta** [comment]
Oh shet I missed that, but at the moment it says "you can't enter a port lower than 16384" :/

**Comment by BrainOffMeta** [comment]
My router is called "Free Revolution", and it's fucked xD

**Comment by VP-EN** [comment]
You should be able to do that yes. Not sure what to do about that router setting, if you can't go lower than 16384. Sounds weird.

But remember to edit the `start_valheim.sh` file as well with the new port, if the `menu.sh` doesn't do it for you. Atleast you should double check 😄

**Comment by BrainOffMeta** [comment]
Yess I'm gonna check that right now :D
Thanks again ! <3

**Comment by VP-EN** [comment]
Forgot to add, you _should_ be able to check your server with [the website](https://geekstrom.de/valheim/check/) from before, as long as you enter the full IP address with the specified port. E.g.  `88.X.178.49:22456`

**Comment by BrainOffMeta** [comment]
Hell yeah it works !!!
Thank you so much for yout support :D

**Comment by VP-EN** [comment]
Yeah NP mate. You can close the issue, if everything is working 👍

**Comment by BrainOffMeta** [comment]
👍 👍 👍 👍
