### ISSUE TITLE
Server not listening

### ISSUE THREAD

**Issue by larryon** [Nimdy/Dedicated_Valheim_Server_Script#128]
Hello,

Installed the server as the guide suggests but it doesn't look like it's listening to any ports:

`
root@ip-172-31-5-250:/opt/Dedicated_Valheim_Server_Script# systemctl status valheimserver.service
● valheimserver.service - Valheim Server
     Loaded: loaded (/lib/systemd/system/valheimserver.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-03-05 09:29:26 UTC; 3min 30s ago
    Process: 2269 ExecStartPre=/home/steam/steamcmd +login anonymous +force_install_dir /home/steam/valheimserver +app_update 896660 validate +exit (code=exited, status=0/SUCCESS)
   Main PID: 2315 (start_valheim.s)
      Tasks: 35 (limit: 4638)
     Memory: 2.2G
     CGroup: /system.slice/valheimserver.service
             ├─2315 /bin/bash /home/steam/valheimserver/start_valheim.sh
             └─2318 ./valheim_server.x86_64 -name xxx-port 2456 -nographics -batchmode -world xxx-password xxxx -public 1

Mar 05 09:30:16 ip-172-31-5-250 start_valheim.sh[2318]: (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
Mar 05 09:30:33 ip-172-31-5-250 start_valheim.sh[2318]: 03/05/2021 09:30:33: Failed to place all Runestone_Mountains, placed 92 out of 100
Mar 05 09:30:33 ip-172-31-5-250 start_valheim.sh[2318]:
Mar 05 09:30:33 ip-172-31-5-250 start_valheim.sh[2318]: (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
Mar 05 09:30:33 ip-172-31-5-250 start_valheim.sh[2318]: 03/05/2021 09:30:33:  Done generating locations, duration:44704.467 ms
Mar 05 09:30:33 ip-172-31-5-250 start_valheim.sh[2318]:
Mar 05 09:30:33 ip-172-31-5-250 start_valheim.sh[2318]: (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
Mar 05 09:30:33 ip-172-31-5-250 start_valheim.sh[2318]: 03/05/2021 09:30:33: DungeonDB Start 729
Mar 05 09:30:33 ip-172-31-5-250 start_valheim.sh[2318]:
Mar 05 09:30:33 ip-172-31-5-250 start_valheim.sh[2318]: (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
`

`root@ip-172-31-5-250:/opt/Dedicated_Valheim_Server_Script# netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      386/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      654/sshd: /usr/sbin
tcp6       0      0 :::22                   :::*                    LISTEN      654/sshd: /usr/sbin
`

Have I done something wrong?

**Comment by Nimdy** [comment]
nc -uv localhost 2456

issue resolved in discord
