### ISSUE TITLE
Accidentaly Overwrite The World File

### ISSUE THREAD

**Issue by mihlac** [Nimdy/Dedicated_Valheim_Server_Script#129]
Hello,

When i was trying to reboot the system, the system overwrite my world file with an old version. And all of my progress is gone. Is there any chance to retrieve it back? Thank you.

**Comment by mihlac** [comment]
Because my server didn't run on game. So i needed to restart my server. But when I load my backup and start the server, my last save has gone. And only the low size db file was left. So i asked is there any chance to get it back. Thanks anyway.

**Comment by Nimdy** [comment]
oh. 

No... if its not there... and you didnt make backups yeah its gone.

This also could just be a process issue... it happens.
