### ISSUE TITLE
Intergrating Valheim+ and other mods

### ISSUE THREAD

**Issue by Nimdy** [Nimdy/Dedicated_Valheim_Server_Script#134]
you asked for it... So here it is.

I have successfully intergrated Valheim+ and keeping everything within the swim lanes.

Should you want to use MODS you can... or you can just play vanilla Valheim.

Either way the options is there.  

You can only have ONE mode running... Vanilla Valheim or Valheim+  

I need testers.... meaning... I need to know what happens when people switch back and forth like crazy rabbits... or other issues that will occur.

I do not provide support for Valheim+ because mods can break stuff but I can help you with the basics of Valheim+

More to come.... This is not public release yet.

![newmain](https://user-images.githubusercontent.com/16698453/110220174-1a029a00-7ec4-11eb-9388-b8c442d1e97d.PNG)
![valheim+](https://user-images.githubusercontent.com/16698453/110220175-1b33c700-7ec4-11eb-9e7a-3b81f51833f0.PNG)

**Comment by Nimdy** [comment]
![grouped menus](https://user-images.githubusercontent.com/16698453/110365691-9bce0100-8045-11eb-8117-1743581ac269.png)

**Comment by Nimdy** [comment]
![Uploading grouped menus.png…]()

**Comment by Nimdy** [comment]
![grouped menus](https://user-images.githubusercontent.com/16698453/110365923-e8b1d780-8045-11eb-85e4-3b4aca17d4c4.png)

**Comment by ihardyslide** [comment]
Hi,

I would love to test and provide feedback, how can I?

Br

**Comment by Nimdy** [comment]
https://www.youtube.com/watch?v=668c4d7TQ3Y&t=1219s
