### ISSUE TITLE
Modify the world seed upon initializing

### ISSUE THREAD

**Issue by teelau** [Nimdy/Dedicated_Valheim_Server_Script#135]
Is there a way to modify the world seed upon initializing?

**Comment by Nimdy** [comment]
no sadly, maybe in the future :), we just have to wait on IronGate. Until then, the best way is to launch the game locally on your PC.  Pick the seed you want for your world.  Save the game PRESS F5 type save, and upload that world to your server.

Follow the uploading steps here: https://github.com/Nimdy/Dedicated_Valheim_Server_Script/wiki/Migrate-Valheim-Map-Data-from-server-to-server

and I made a video as well

https://www.youtube.com/watch?v=wdZWxvvWcZ8&t=306s
