### ISSUE TITLE
[Question] How to make player admin? like to execute command 'save' in game console

### ISSUE THREAD

**Issue by shivajivarma** [Nimdy/Dedicated_Valheim_Server_Script#137]

**Comment by VP-EN** [comment]
Hey
Multiple ways to go about this. 

First of, you'll need your `SteamID64`. You can get this from Valheim (ingame):
https://i.imgur.com/pIqXCC4.png

Or you can use a website like [this](https://steamid.xyz/), just enter your steam username, and copy your SteamID64.

After that, you'll need to find your `adminlist.txt` file. For unix/linux, it'll probably be located in:
`/home/steam/.config/unity3d/IronGate/Valheim/adminlist.txt`

Then edit the file to include your SteamID64, like so:
```
// List admin players ID  ONE per line
76561212341234569
```

(not a real ID, insert your SteamID64).

No need for restarting the server, editing and saving the `adminlist.txt` should be sufficient.
