### ISSUE TITLE
Server not showing up in community list

### ISSUE THREAD

**Issue by destiny-creates** [Nimdy/Dedicated_Valheim_Server_Script#14]
modified the very first part of the script for the credentials and world name. also, added option -public 1 to the start command so it would show in community list. after 30 minutes, my server still does not show up in the community list. followed every step. including port forwarding.

**Comment by destiny-creates** [comment]
i see there is a fix for this, please do include this in the readme. found in closed issues

**Comment by Nimdy** [comment]
-public 1 is hit or miss and this is why it doesnt matter if it is listed in the code or not.

I have servers that show up in the list and they do not use -public 1

https://github.com/Nimdy/Dedicated_Valheim_Server_Script/wiki/Top-10-Reason-your-Server-is-not-working-and-how-to-fix

I am trying to clean up the readme.  I will work on that today.

**Comment by Nimdy** [comment]
Also  -public 1 has been removed since day 1. Thanks @beko!

**Comment by destiny-creates** [comment]
removed how? like its not an option
