### ISSUE TITLE
system completely changed after install

### ISSUE THREAD

**Issue by LarsOde** [Nimdy/Dedicated_Valheim_Server_Script#147]
Hi,

I used my root server for installing this, and already during install I saw a lot of "uninstalling" messages rushing through. After installation finished, my system was quite completely blank of anything I had running before: webserver, plesk software, database etc. Is this intended? It looks like a complete system rebuild ;)
Is there any way to get the system back to it's former state, AND have valheim installed? Otherwise I'd have to restore a snapshot and won't be able to run a dedicated server there (or is there some manual installation guide that leaves the system intact?)

**Comment by Nimdy** [comment]
I don't know what commands you ran but the script doesn't remove software. Unless github was hacked .

Type history

And paste all that

**Comment by LarsOde** [comment]
I'm already doing a restore now... I guess it's some apt installation, that forced removal of a lot of stuff (I don't think github is hacked ;))

That's the process list after reboot, not much left for a webserver with plesk ;)

USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.3  0.0 224912  8708 ?        Ss   22:15   0:00 init -z
root        70  0.2  0.1 119384 23976 ?        Ss   22:15   0:00 /lib/systemd/systemd-journald
root        83  0.0  0.0  42100  3452 ?        Ss   22:15   0:00 /lib/systemd/systemd-udevd
systemd+   169  0.0  0.0  70660  5252 ?        Ss   22:15   0:00 /lib/systemd/systemd-resolved
root       172  0.0  0.0  70608  6052 ?        Ss   22:15   0:00 /lib/systemd/systemd-logind
syslog     173  0.0  0.0 263028  4192 ?        Ssl  22:15   0:00 /usr/sbin/rsyslogd -n
root       178  0.0  0.0  30352  3212 ?        Ss   22:15   0:00 /usr/sbin/cron -f
root       179  0.2  0.1 169424 17268 ?        Ssl  22:15   0:00 /usr/bin/python3 /usr/bin/networkd-dispatcher --run-startup-triggers
message+   180  0.0  0.0  49924  4300 ?        Ss   22:15   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
root       241  0.0  0.1 439484 26540 ?        Ss   22:15   0:00 php-fpm: master process (/etc/php/7.2/fpm/php-fpm.conf)
root       245  0.1  0.1 186264 20280 ?        Ssl  22:15   0:00 /usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal
root       263  0.0  0.0  14988  2368 ?        Ss+  22:15   0:00 /sbin/agetty -o -p -- \u --noclear --keep-baud console 115200,38400,9600 linux
tss        272  3.3  0.1 1692064 29280 ?       Sl   22:15   0:01 /home/tss/ts3/ts3server inifile=/home/tss/ts3/ts3server.ini
root       273  0.0  0.0  13016  1916 ?        Ss+  22:15   0:00 /sbin/agetty -o -p -- \u --noclear tty2 linux
root       297  0.0  0.0  72296  5696 ?        Ss   22:15   0:00 /usr/sbin/sshd -D
root       303  0.0  0.0  24184  2548 ?        Ss   22:15   0:00 /usr/sbin/xinetd -pidfile /run/xinetd.pid -stayalive
root       320  0.0  0.0  39888  1504 ?        Ss   22:15   0:00 sw-cp-server: master process /usr/sbin/sw-cp-serverd -c /etc/sw-cp-server/config
sw-cp-s+   321  0.0  0.0  44812  4532 ?        S    22:15   0:00 sw-cp-server: worker process
mysql      353  1.1  1.1 1357496 194692 ?      Sl   22:15   0:00 /usr/sbin/mysqld --daemonize --pid-file=/run/mysqld/mysqld.pid
www-data   355  0.0  0.0 441780 12960 ?        S    22:15   0:00 php-fpm: pool www
www-data   356  0.0  0.0 441780 12960 ?        S    22:15   0:00 php-fpm: pool www
www-data   410  0.0  0.0  19900   172 ?        Ss   22:15   0:00 /usr/bin/htcacheclean -d 120 -p /var/cache/apache2/mod_cache_disk -l 300M -n
root       513  0.0  0.0  65440  3144 ?        Ss   22:15   0:00 /usr/lib/postfix/sbin/master -w
postfix    514  0.0  0.0  85424  6248 ?        S    22:15   0:00 pickup -l -t fifo -u -c
postfix    515  0.0  0.0  85484  6296 ?        S    22:15   0:00 qmgr -l -t fifo -u
root       573  0.0  0.0 101564  7044 ?        Ss   22:15   0:00 sshd: xxxxxxx [priv]
xxxxxxxx   652  0.0  0.0 103860  5504 ?        S    22:15   0:00 sshd: xxxxxx@pts/0
xxxxxxxx   653  0.1  0.0  22192  5376 pts/0    Ss   22:15   0:00 -sh
root       671  0.0  0.0  58644  4360 pts/0    S    22:16   0:00 sudo su -
steam      674  0.0  0.0  11916  3276 ?        Ss   22:16   0:00 /bin/bash /home/steam/valheimserver/start_valheim.sh
steam      676 75.3  4.3 5648636 728204 ?      Sl   22:16   0:08 ./valheim_server.x86_64 -name xxxxxx -port 2456 -nographics -batchmode -world RaaHoorKhuit -password xxxxxxxx -public 1
root       707  0.0  0.0  57944  3772 pts/0    S    22:16   0:00 su -
root       708  2.0  0.0  22064  5312 pts/0    S    22:16   0:00 -su
root       722  0.0  0.0  36400  3328 pts/0    R+   22:16   0:00 ps aux

**Comment by LarsOde** [comment]
I will first update my ubuntu again to 18 today (as I just did before the install), so that my providers auto update can grab that tomorrow morning, and in case of another restore I will at least keep the OS version up (I only have a daily backup). Then I will try again tomorrow. Is the scripts output logged? Otherwise I'll probably use a screen session for logging

**Comment by Nimdy** [comment]
lol github hacked... yeah I was joking :)

The script doesnt uninstall anything.

So I am confused on why... whatever happened... happened...

logs? no it doesnt make logs. You can view /var/log/syslog and all the information would be dump there.

**Comment by Nimdy** [comment]
https://github.com/Nimdy/Dedicated_Valheim_Server_Script/wiki

**Comment by Nimdy** [comment]
i would never install anything on a production server, until you test it in a dev box... 

I cannot reproduce this.
