### ISSUE TITLE
Incompatible Version

### ISSUE THREAD

**Issue by christanplaza** [Nimdy/Dedicated_Valheim_Server_Script#150]
So I am currently hosting a Valheim server for friends via GCP. Late last night, we were encountering a very hard de-sync within the server (No one could interact with any objects), so we decided to restart the server.

Upon doing so, I also updated the Admin Menu, which pulled the version with the `advancemenu.sh`, and I decided to use that to restart the server.

Now we aren't able to connect to the server due to the Incompatible Version error. I've tried updating the Server Client multiple times with both menu and advancemenu.

Did I do something wrong? The update function does say it is updated, but I'm not sure if it persists.

Any kind of help would be appreciated.

Server Specs:
Ubuntu 20.04.2 LTS

**Comment by Nimdy** [comment]
Make sure everybody has a paid copy of the game.

Unless there was a server update... then you shouldnt have that issue.

I would look through there.  
https://valheimbugs.featureupvote.com/


This is not a script issues

**Comment by dreamalligator** [comment]
> dmin Menu, which pulled the version with the `advancemenu.sh`, and I decided to use that to restart the server.
> 
> Now we aren't able to connect to the server due t

Exact same thing happened to me today with not interacting, using the dedicated server script to check for updates, restart service, got incompatible version error. 

Does activating the menu with or without sudo matter if I'm a root user in Digital Ocean Ubuntu 20.04.2 droplet? Does touching any of the mod menu, even if I don't install mods matter?

**Comment by Nimdy** [comment]
**### Are you using mods?**


If you are root, you dont need sudo

Check your logs

cat /var/log/syslog

and

journalctl --unit=valheimserver --reverse



Either your game client if off or your server client.
