### ISSUE TITLE
Server keeps going inactive

### ISSUE THREAD

**Issue by HeadAdmiral** [Nimdy/Dedicated_Valheim_Server_Script#166]
For some reason, the server keeps going from `active` to `inactive`. It happens consistently after it has been running for a while with nobody connected, but it also happened while someone was on the server and playing. This means that I have to remote into the server and start the process multiple times throughout the day.

The server runs fine and works as it should otherwise. Just a bit annoying to have to restart it 3+ times per day. 

Not sure if this is an issue with the Valheim server executable itself or the script.

**Comment by Nimdy** [comment]
what do you logs show

**Comment by Nimdy** [comment]
i am going to guess.... 

resources...or password is not unique.

https://github.com/Nimdy/Dedicated_Valheim_Server_Script/wiki/Top-10-Reason-your-Server-is-not-working-and-how-to-fix

**Comment by Nimdy** [comment]
Check your syslogs.... look for out of memory errors...

Let me know :)

**Comment by HeadAdmiral** [comment]
The server is an Ubuntu droplet on DigitalOcean, $20/mo plan, so 2 CPUs and 4GB RAM. So the specs are the recommended minimum. 

You are right, it's an out of memory error. 
Ran `grep oom /var/log/*` and got the following:
![image](https://user-images.githubusercontent.com/19769539/110754172-1d23c000-820d-11eb-9a2a-219a26d2a124.png)

Running `watch -n 5 free -m` yields this without the server running:
![image](https://user-images.githubusercontent.com/19769539/110754766-c7034c80-820d-11eb-9e14-692506281c24.png)

And with it running:
![image](https://user-images.githubusercontent.com/19769539/110754917-f5812780-820d-11eb-80d0-ca1b9c26af0d.png)

So it seems like 2 CPUS, 4GB RAM is sufficient, but only _just_ barely. I'll increase the resources and see if that fixes the issue.

**Comment by Nimdy** [comment]
Let me know... Normally, I have seen 4GB ram work... but once the world get used a lot (building, exploring...etc), it starts to crash.

I am hoping IronGate does a lot more optimization in the future.

I run 4CPU 8GB ram.... no issues since day one.  The only thing we experience is the commonly known issues from Official Valheim Bug Tracker.

Once I get back to playing again and testing... I will do some outside the box stuff to see if I cant force better processing of game data and the handling of processes.  


Keep in touch!

**Comment by HeadAdmiral** [comment]
If you don't mind me asking, how did you get access to the $40/mo plan? I put in a request to get access, but the response I got was to wait a month or pay upfront. I'm willing to pay the 25% upfront to unlock that tier, but I can't find anywhere to do so.
