### ISSUE TITLE
Attempting to join manually: Disconnected

### ISSUE THREAD

**Issue by Vanclief** [Nimdy/Dedicated_Valheim_Server_Script#167]
I am having issues with setting up a server instance.

1. Created Digital Ocean instance with 2 CPU and 4GB.
2. Installed following the instructions
3. Applied enabled ports in `ufw`
4. Applied Digital Ocean section from this config https://github.com/Nimdy/Dedicated_Valheim_Server_Script/wiki/AWS-Azure-GCP-and-DigitalOcean-Valheim-Port-Configuration
5. Server appears Ok in https://geekstrom.de/valheim/check/ but not in game.
6. When attempting to connect manually to the server, I get "Disconnected" message after loading screen.

Checked troubleshooting, but could not find solution to my problem.
https://github.com/Nimdy/Dedicated_Valheim_Server_Script/wiki/Top-10-Reason-your-Server-is-not-working-and-how-to-fix

**Comment by Vanclief** [comment]
Nuked everything and tried again from a new droplet with the same error.

**Comment by Nimdy** [comment]
issues fixed. Was using wrong IP address :)
