### ISSUE TITLE
Mod support?

### ISSUE THREAD

**Issue by pieterhouwen** [Nimdy/Dedicated_Valheim_Server_Script#17]
Hello, do you have any idea on how to use mods in the dedicated server?

**Comment by Nimdy** [comment]
not yet... not trying yet... still way early access but when they do... full tuts coming!

**Comment by JoaopfRodrigues** [comment]
I'm finding that modified server files are overwritten when the server is restarted. Is this related to the steam update validation? 

For example, on this line: https://github.com/Nimdy/Dedicated_Valheim_Server_Script/blob/e0cb331d52bcf50998ba7c3ef071b96b65874fcd/menu.sh#L286

I see that the validate argument is used. Could that be the cause? Is there any workaround that would allow modified dll's to run on the server?

Thank you

**Comment by Nimdy** [comment]
> I'm finding that modified server files are overwritten when the server is restarted. Is this related to the steam update validation?
> 
> For example, on this line:
> 
> https://github.com/Nimdy/Dedicated_Valheim_Server_Script/blob/e0cb331d52bcf50998ba7c3ef071b96b65874fcd/menu.sh#L286
> 
> I see that the validate argument is used. Could that be the cause? Is there any workaround that would allow modified dll's to run on the server?
> 
> Thank you

This is the default check/update/apply from Valheim I believe it does it nightly... but I have to confirm.


I have only done a little R&D part of Valheim because of how early access it is... Too many changes coming... not trying to mess anything up.
