### ISSUE TITLE
[BUG] Incorrect server naming if there is a space

### ISSUE THREAD

**Issue by ShikyoKira** [Nimdy/Dedicated_Valheim_Server_Script#197]
If the server name has a space for example "The server name", only "The" will be shown in client PC

1. Have a server name with space
2. Start the server with mods enabled
3. Refresh client server list

**Comment by Nimdy** [comment]
strange....
![Capture](https://user-images.githubusercontent.com/16698453/111376954-6908b600-86a0-11eb-8f20-38e7fd400ab6.PNG)

seems to be just correct...

**Comment by Nimdy** [comment]
![Capture](https://user-images.githubusercontent.com/16698453/111377277-bdac3100-86a0-11eb-8445-78454f7c2a3c.PNG)
from the advance menu now

**Comment by Nimdy** [comment]
i need help reproducing this? I am unable

**Comment by Nimdy** [comment]
i believe I did more than just fix this.

Rebuild your config file by enabling public... even if its already enabled.

stop your valheim server and then start it again

You server should also now show up in the public listing as well

**Comment by djmarley** [comment]
I had the same issue, but it only happened when running with mods enabled. I ended up adding quotes around ${server_name} in start_server_bepinex.sh and it seemed to fix the problem.

**Comment by Nimdy** [comment]
i am confused again...

`"${VALHEIM_PLUS_PATH}/${executable_name}" -name "${server_name}" -password "${server_password}" -port "${server_port}" -world "${server_world}" -public "${server_public}"`

**Comment by Nimdy** [comment]
btw I have tested about 50 plus installed today... The Public listings are still hit or miss

I would have one show up and restart the service... never popped up again.... steamclient.so is solid too...  These are the same issues ARK still has today... so who knows... I will keep trying though

**Comment by djmarley** [comment]
Hopefully this helps! Here's the last line I edited with the added quotes around ${server_name}. My full server name now shows, even after restarts.

> "${PWD}/${executable_name}" -name "${server_name}" -password ${server_password} -port ${server_port} -world ${server_world} -public ${server_public}

**Comment by Nimdy** [comment]
thanks what version of the menu are you running?

**Comment by Nimdy** [comment]
yeah that was teh last version from v+

They released a emergent patch after and I applied it to the new update.

**Comment by Nimdy** [comment]
https://github.com/Nimdy/Dedicated_Valheim_Server_Script/search?q=%7BPWD%7D

yeah ${PWD} isnt even found in my repo anymore :(, it was updated... V+ had issues... 

Thanks for the help though :)
