### ISSUE TITLE
[FEATURE]On initial debian installation, sudo missing

### ISSUE THREAD

**Issue by nickosgr** [Nimdy/Dedicated_Valheim_Server_Script#208]
I recently  found out contabo and wanted to test setting up a server there since it seems very cheap. I setup a Debian 10 and tried the scripts, which all worked up to the point where any sudo command was used. For example on stopping the server (which btw started normally) i would get this:
Stopping Valheim Server Services
/opt/Dedicated_Valheim_Server_Script/menu.sh: line 687: sudo: command not found

I realised sudo was inexistent in this system and started looking for how to install since i havent had this issue before, when i came around this solution [on unix stackexchange](https://unix.stackexchange.com/questions/354928/bash-sudo-command-not-found) that fixes it on a couple of commands and works perfectly afterwards

Perhaps it is unusual and unnecessary but since i came across the issue i thought i should let you know.

**Comment by Nimdy** [comment]
not sure if adding this is really required... but this was not built for deb even though Ubuntu is built off deb... and sudo should be installed... that is a very common install.... 

When people have issues like this, the hosting company has misconfigured ISO deployments.

I will talk it over with others.... 


TL:DR- sudo should be installed ...

**Comment by Nimdy** [comment]
also... I dont think I need sudo in those areas as well because you already have to sudo to use the menu....

**Comment by Nimdy** [comment]
I will remove sudo.... not sure why I put that in there...

**Comment by nickosgr** [comment]
> not sure if adding this is really required... but this was not built for deb even though Ubuntu is built off deb... and sudo should be installed... that is a very common install....
> 
> When people have issues like this, the hosting company has misconfigured ISO deployments.
> 
> I will talk it over with others....
> 
> TL:DR- sudo should be installed ...

It is true its probably not a good ISO deployment but it was a cheap server so i thought i should try it ^^ and should i have chosen ubuntu i probably wouldnt have any issue to begin with XD 

Since i dont have too much experience with linux but so far each of them had sudo by default i did not even know it was possible to not have. 

It works just fine on debian so far btw ^^ so thats nice

**Comment by Nimdy** [comment]
thank you
