### ISSUE TITLE
User Account Creation Fails - password with spaces

### ISSUE THREAD

**Issue by Jake-Etherflow** [Nimdy/Dedicated_Valheim_Server_Script#21]
I used a password with spaces in the user password string and the script failed to create the account. Removed the spaces and it worked like a charm.

**Comment by Nimdy** [comment]
Thanks Jake.  

Also special chars will break it as well $%^&*#@!, even without the script.  If people use the default installer from steamcmd... it will not work, if you add those spec-chars
