### ISSUE TITLE
[FEATURE] Install only BepInEx

### ISSUE THREAD

**Issue by D-A-R-K-N-E-S-S** [Nimdy/Dedicated_Valheim_Server_Script#217]
For those of us that do not use Valheim+, but only BepInEx - it would be great if there could be a separate option to install and update only BepInEx. I know the Valheim+ menu option includes BepInEx but it will not update to the latest BepInEX unless the Valheim+ release has updated it. For example, BepInEx has been updated to 5.4.9 but Valheim+ is still using the 5.4.8 version.

Thank you for all of your work on the menu.

**Comment by Nimdy** [comment]
Okay!

:)

Easy enough... I just hope people dont get confused :)

**Comment by VP-EN** [comment]
Can't use the official [BepInEx repo](https://github.com/BepInEx/BepInEx/releases/latest) though, since there's an [issue with some DLLs not included](https://github.com/NeighTools/UnityDoorstop/issues/10#issuecomment-776921796), hence why the [denikson pack](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/) is needed for Valheim.

Just FYI

**Comment by Nimdy** [comment]
FYI: I have started on this... I will need some testing later... stuff might break lol

**Comment by Voarexxx** [comment]
> FYI: I have started on this... I will need some testing later... stuff might break lol

I love breaking stuff xD

**Comment by D-A-R-K-N-E-S-S** [comment]
Thank you Nimdy for attempting to include this feature, really appeciate it!

Just want to echo what VP-EN commented on - the standard denikson pack includes the necessary stripped dlls. The full pack is more geared towards plugin developers and not necessary to host mods.

**Comment by Nimdy** [comment]
https://github.com/Nimdy/Dedicated_Valheim_Server_Script/blob/beta/advancemenu.sh

I am almost done. I need to test it and get everything working correctly before I publish it.

**Comment by Nimdy** [comment]
completed. Enjoy...Everything seemed to work on a fresh system... soooooo
