### ISSUE TITLE
[BUG] Confusing Server Version Info

### ISSUE THREAD

**Issue by Pendora2017** [Nimdy/Dedicated_Valheim_Server_Script#220]
**Describe the bug**
I find the server version info in the menu header a little bit confusing... today as the new patch is released i took a look into the script to see if there's a new version... Official Build Version smaller than my Server Version? WTF ... must i downgrade? :D

**Expected behavior**
Installed Version: v.1.1
Offical Version: v1.2

underneath a new line red coloured: "--- Update avaiable ---"

**Screenshots**
Before Update:
![Vor dem Update](https://user-images.githubusercontent.com/28994273/112203125-7bd83900-8c12-11eb-8d8c-90b4fa9da447.png)

After Update:
![Nach dem Update](https://user-images.githubusercontent.com/28994273/112203151-8266b080-8c12-11eb-8e37-3730f1783c0f.png)

**Hosting Company (please complete the following information):**
Ubuntu 20.04 LTS self hosted

**Comment by Nimdy** [comment]
yeah... we have a fix... Thank you

**Comment by Nimdy** [comment]
Will be added in next menu update:

https://github.com/Nimdy/Dedicated_Valheim_Server_Script/blob/38f788b80bf033ba04180705eafbdcbf1b104cd9/menu.sh#L1091
