### ISSUE TITLE
[BUG] Incompatible Version

### ISSUE THREAD

**Issue by Voarexxx** [Nimdy/Dedicated_Valheim_Server_Script#222]
- **Linux Server**
- **Valheim Game Version:** [0.148.6]
- **V+ Mod Version:** [0.9.6]

**Incompatible Version**

I've recently updated to the latest versions on the client and the server and it is saying my friends and I have an Incompatible Version. I use a PowerShell script to update locally that is coded to automatically pull your latest version and has been working fine until the recent update.

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. Update Valheim Plus using the server menu. 
2. Go to 'https://github.com/Voarexxx/valheim_plus_client_update_tool'
3. Click on 'Download Zip'
4. Open file to go through the PowerShell notes if you wish prior to running the script. 
5. After reviewing those files, you can open file location and run the script in PowerShell, though you probably won't need it if you are just wanting to read the script.
6. Incompatible Version upon logging into the Valheim Plus server.

**SIDE NOTE**
Without using the .sh script I also updated my local files and this is still occurring. 

**Expected behavior**

My Valheim server with Valheim Plus mod enabled says version 0.9.6 but when I go to the game and login to the server it says "Incompatible Version". 

**Troubleshooting**

 I ran the updates again using the Valheim Plus menu just to verify, and am still getting same issue. All the version are accurate, 0.9.6 and I've updated local files and even uninstalled and reinstalled. I legit have no clue why my server is incompatible, but it's completely up to date. 

**Screenshots**

Unsure if applicable

**Link to [Voarexxx/valheim_settings](https://github.com/Voarexxx/valheim_settings) containing .cfg configuration if applicable:**

**Additional context**

I've done everything I can think of. I have updated and installed and disabled and re-enabled Valheim Plus mods on the server. I've updated the values. All the server information shows as 0.9.6. I even updated the server files with git add files for the new files for logs. *shrug* Please help.

**Comment by prolok** [comment]
Just a sharing here: I have recently do the update, and simply "14) Restart Valheim Server" but still get the "Incompatible Version" in game.

However when I do "16) Backup World Data" and let it stop and start the server again, then I can get into it successfully. Maybe you can try stop and start the server separately, see if it works or not?

**Comment by Nimdy** [comment]
You have something else going on.

You should have completed this with the following steps:

Update Valheim
Update ValheimPlus
Download the New Valheim PLus client files required for the game client
Unpacked the files from WindowsClient.zip and overwrite your Game client Valheim install
Restart Valheim Service on your Dedicated Server
View your logs in Valheim syslog or whatever logging you are using
cat /var/log/syslog
Look for errors
Figure out the errors, if you have any.

Other folks have no issues and if you are having issues, then you have something out of baseline or you have misconfigurations somewhere else.

![proof](https://user-images.githubusercontent.com/16698453/112363327-ab03ae80-8cd5-11eb-8c26-5372dac49ef1.PNG)

If you are still having issues, then you need to read the logs or post them here and I will tell you WHY your ValheimPlus update is not working.

**Comment by Voarexxx** [comment]
> You have something else going on.
> 
> You should have completed this with the following steps:
> 
> Update Valheim
> Update ValheimPlus
> Download the New Valheim PLus client files required for the game client
> Unpacked the files from WindowsClient.zip and overwrite your Game client Valheim install
> Restart Valheim Service on your Dedicated Server
> View your logs in Valheim syslog or whatever logging you are using
> cat /var/log/syslog
> Look for errors
> Figure out the errors, if you have any.
> 
> Other folks have no issues and if you are having issues, then you have something out of baseline or you have misconfigurations somewhere else.
> 
> ![proof](https://user-images.githubusercontent.com/16698453/112363327-ab03ae80-8cd5-11eb-8c26-5372dac49ef1.PNG)
> 
> If you are still having issues, then you need to read the logs or post them here and I will tell you WHY your ValheimPlus update is not working or why you can not connect to your server.
> 
> Posting logs in the future will help out a ton. Please strip your PASSWORD out for safety or privacy or whatever...

I was worried it was a ValheimPlus issue because your version says up to date, and the menu is all up to date and mods are enabled and everything is proper but ValheimPlus they also said that everything was right on their end... I have properly updated my local files, I deleted all the old ones and manually updated them. I was working fine on the 0.9.5.5 version with your menu and nothing was wrong, even on the updated 0.9.6 nothing is wrong on your menu. I even added the new log files and what not. I updated everything. I'm relatively NEW to coding so my best friend has taught me a lot but I have much to learn. No idea how to share additional files except for the ones I linked above. They have all the files I think. On lunch or after work I will try again but my best friend is probs over helping me with my Valheim coding issues lolol. My .sh script it erroring out and it used to not error out. Sigh. I wish Loki would quit his shit. lol! I'll update soon to see if I can fix anything. For now, I'll close the ticket.

**Comment by Nimdy** [comment]
You can jump into discord and I will help you

**Comment by Voarexxx** [comment]
Voarexxx#6207

**Comment by Nimdy** [comment]
100% completed...

rewalked through all the steps... rebooted... no issues

**Comment by Voarexxx** [comment]
^ This dude is the man!

**Comment by Nimdy** [comment]
No problem

**Comment by Voarexxx** [comment]
Hey Nimdy,
     I am still receiving the Incompatible Version. After you helped me earlier, the server was up and running but not with Valheim Plus, just the normal Valheim? I'm not sure what to do here. :( I have legit tried so much and I know you've helped so much haha so I truly appreciate it. I'll re-close this ticket if you need me to, but I just don't understand how I am not able to play :<


[Player.github.log](https://github.com/Nimdy/Dedicated_Valheim_Server_Script/files/6202137/Player.github.log)

<img width="301" alt="vplus2" src="https://user-images.githubusercontent.com/80941695/112421407-95ea4800-8cf4-11eb-8906-16a23ab79b42.png">

<img width="1496" alt="vplus" src="https://user-images.githubusercontent.com/80941695/112421419-9aaefc00-8cf4-11eb-8004-458ad9f6a81a.png">

**Comment by Voarexxx** [comment]
Was very helpful found the root cause of the issue was error due to recent updates from Valheim Plus made permissions need to be steam user for all files.

**Comment by Nimdy** [comment]
using a outside script(not baseline script from Njord Menu) to pull custom configuration files and not setting permissions back to steam...
