### ISSUE TITLE
[BUG] Update server version

### ISSUE THREAD

**Issue by vinbeze** [Nimdy/Dedicated_Valheim_Server_Script#230]
**Describe the bug**
When trying to use the menu.sh to update the valheim server, the update is not occurring.

current version of my server: Valheim Server Build: 6394774
latest build version: Valheim Official Build: 6315977

after using the command the server remains at the same version - Valheim Server Build: 6394774

**To Reproduce**
1. cd /opt/Dedicated_Valheim_Server_Script
2. ./menu.sh
3. 4) Check and Apply Valheim Server Update
4. ENTER

**Expected behavior**
the server should update with the latest build version available

**Screenshots**
![teste1](https://user-images.githubusercontent.com/17272288/112722661-a0216780-8ee9-11eb-8449-5ce3a4fe9112.jpg)
![teste2](https://user-images.githubusercontent.com/17272288/112722665-a3b4ee80-8ee9-11eb-8dda-5246a5f9b6f5.jpg)

**Hosting Company (please complete the following information):**
 - Cloud Provider: [Google Cloud Platform]

I apologize for my English, I am a Brazilian user.

**Comment by Nimdy** [comment]
new version fixes that... we had to do some magic

**Comment by geekthought** [comment]
Nope, not fixed here. Still no update occuring... 

Valheim Official Build: 6394774
Valheim Server Build:  6437354

**Comment by Nimdy** [comment]
![image](https://user-images.githubusercontent.com/16698453/112856028-aeb97b80-90af-11eb-92f5-be4a38f0609f.png)

**Comment by Nimdy** [comment]
![image](https://user-images.githubusercontent.com/16698453/112856092-bda02e00-90af-11eb-937c-21197b5ca376.png)

**Comment by vinbeze** [comment]
Dear, I have the script in the latest version, but even then the error persists

**Comment by VP-EN** [comment]
Did you restart the server after applying the update? 
As in `sudo service valheimserver restart` or `sudo systemctl valheimserver restart`

**Comment by vinbeze** [comment]
I just tested the restart that you suggested, and the error still persists.

Is there any way I can force the update?

**Comment by Nimdy** [comment]
update the menu

This will now delete the the cache file if the stamp is older than 1 hour.

The menu should hang for 4 seconds... or so... and then printout the new cache
find "/home/steam/valheimserver/officialvalheimbuild" -mmin +59 -print

**Comment by SourSun** [comment]
I had the same issue an hour ago, updated the menu, re-ran the update script still no luck. (Although players were now getting a connection error not version error, this could have been my bad)
In the end I just backed-up the world and ran a reinstallation of the server, seems to have updated the server atleast.

**Comment by vinbeze** [comment]
@Nimdy, I reinstalled the server as @SourSun  suggested and it worked, thank you very much
