### ISSUE TITLE
[FEATURE] Dark Background Detection? Remove dark blue color on 'su'?

### ISSUE THREAD

**Issue by Romaq** [Nimdy/Dedicated_Valheim_Server_Script#231]
Problem: When the script detects a password needed for "su", it displays a dark blue password request on my black background.

1) There may be a tweak I can do on /root/.bashrc or /home/<user>/.bashrc that I'm unaware of, but "su" does what it does... IN COLOR! Which would be 'nice' if it were not dark blue on my black background.
2) /etc/vim/vimrc has a line "set background=dark" I can invoke so vi doesn't do this to me. It would be happy if either a) color were stripped from the invoke of sudo, or b) su has this sort of configuration so I can edit *that* and be done with this without you doing anything.

I don't see a config file in /opt/Dedicated_Valheim_Server_Script, which would make *adding* one highly undesirable. I can futz with Putty "color" values to switch to a white background and invert everything else as necessary, but I prefer "night mode" and I'd really rather just tweak something in the right spot.

But my searchFU is weak, and I couldn't find anything leading to making sense of the su login prompt being in color. Would anyone have ideas so the Valheim script doesn't need any changes JUST for the su login prompt?

**Comment by Nimdy** [comment]
https://darekkay.com/blog/my-putty-color-scheme/

You would have to google making or adding putty themes... Or Ubuntu Shell/Terminal theme... or shell themes..

I never really have played with it much...

**Comment by Romaq** [comment]
Thank you! That absolutely does the trick and resolves the problem without you having to code anything... the best fix. :) I apologize for not knowing what I was looking for when the problem occurred.
