### ISSUE TITLE
wan access issue possible apache

### ISSUE THREAD

**Issue by haviduck** [Nimdy/Dedicated_Valheim_Server_Script#234]
- **Hosted Status:** [Local Home Server]
- **Valheim Game Version:** 0.1.48.7
os: Ubuntu 18.04
cpus: 24
mem:146
router: pfsense

heya!
i installed and everything works fine when i connect to internal ip. the "is my valheim server up" app says my server is running etc. but i cant access it from wan. during install i saw a brief apache2 error. my rig is running nginx. so i was just wondering if that might be the issue. 

any tips or tricks?

**Comment by Nimdy** [comment]
Did you try this

https://github.com/Nimdy/Dedicated_Valheim_Server_Script/wiki/How-to-Valheim-Server-Port-Configuration:-DigitalOcean,-AWS,-Azure-and-GCP#home-pfsense

**Comment by haviduck** [comment]
> Did you try this
> 
> https://github.com/Nimdy/Dedicated_Valheim_Server_Script/wiki/How-to-Valheim-Server-Port-Configuration:-DigitalOcean,-AWS,-Azure-and-GCP#home-pfsense

yeah, but i think it might be a subnet issue or some other weird networking thing i probably should know about ^^ i'll continue trying and will post any solutions. thanks for building a cool server btw, love the menus.

**Comment by Nimdy** [comment]
glad you worked it out
