### ISSUE TITLE
World Data not saving after copying world data from computer [TECH SUPPORT}

### ISSUE THREAD

**Issue by lukasasorensen** [Nimdy/Dedicated_Valheim_Server_Script#237]
I'm hosting on AWS lightsail. I followed the documentation to copy over my world data. my permissions all look correct, but when I try to test it out by going into the world, making some changes and then logging out. I'm not seeing the .db or .fwl files being updated. Any help at all is greatly appreciated.

<img width="1098" alt="Screen Shot 2021-03-31 at 4 32 13 PM" src="https://user-images.githubusercontent.com/4251834/113214256-d5f28300-923e-11eb-8db0-11b92b69b8b9.png">

**Comment by lukasasorensen** [comment]
nvm, It's actually working. Sorry about that.

**Comment by wota-n** [comment]
This screenshot saved my life. For some reason Git Bash does not print the first line about the file directories when printing the world data saves details.
