### ISSUE TITLE
[BUG] Unable to use Some Tech support Tools

### ISSUE THREAD

**Issue by NeonMeth** [Nimdy/Dedicated_Valheim_Server_Script#238]
So far this server script menu has been working flawlessly, Great work. You helped make this 100x easier

However I haven't had any luck using Option 2 for Tech Support tools

Doing Display Config file gives me the following then back to the menu:

```
#
!/bin/bash
export templdpath=$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=./linux64:$LD_LIBRARY_PATH
export SteamAppId=892970
# Tip: Make a local copy of this script to avoid it being overwritten by steam.
# NOTE: You need to make sure the ports 2456-2458 is being forwarded to your server through your local router & firewall.
./valheim_server.x86_64 -name "Muddholm" -port "2456" -nographics -batchmode -world "MuddholmWorld" -password "Mudd1"
#export LD_LIBRARY_PATH=
export LD_LIBRARY_PATH=$templdpath
```

Doing 6- Connected Players History gives me nothing, just goes right back to the menu
And for 7 Server Logs it gives me: Binary file (standard input) matches

As for the other options they work as intended. Is there an app or something Im supposed to install?  Would appreciate any help

**Comment by Nimdy** [comment]
I just tested the menu and advancemenu... all the options work under Tech Support....

6 is just looking for :
sudo grep ZDOID /var/log/syslog*

If you want to look at all your logs, everything dump in the syslog or you can 

journalctl --unit=valheimserver --reverse

let me know

**Comment by Nimdy** [comment]
or try

grep -w 'warning|error|Info|oom\Error' /var/log/syslog*

**Comment by NeonMeth** [comment]
(Sorry I'm a bit of a noob)
Under what directory would I be running all 3 commands under?

Also might help mentioning Im running on basic Ubuntu

**Comment by NeonMeth** [comment]
Also would the world directory be located within: /home/steam/.config/unity3d/IronGate/Valheim$
