### ISSUE TITLE
How to access to the console server ?

### ISSUE THREAD

**Issue by SonzoFR** [Nimdy/Dedicated_Valheim_Server_Script#24]
Hello
Could you please tell me how to access valheim server console ?
For use Valheim server admin console commands like : 
https://www.windowscentral.com/every-valheim-console-command-and-cheat
Thanks in advance.

**Comment by Nimdy** [comment]
oh that website you posted it states you must do the following:

To get started, open up your game, and once loaded, press F5 to open the console command, and type iamacheater to activate cheats. Type it again to deactivate cheats.

**Comment by SonzoFR** [comment]
No, I'm talking about the console from the linux machine! Not from the game ;)

**Comment by Nimdy** [comment]
haven't got to that yet but if you find out please let me know.
