### ISSUE TITLE
[TECH SUPPORT} - Menu not working

### ISSUE THREAD

**Issue by GJordao** [Nimdy/Dedicated_Valheim_Server_Script#250]
- **Hosted Status:** [Local Home Server]
- **Valheim Game Version:** [0.148.7]
- **Type of Request:** [Scripting]

My server is currently running but when I try to access the menu it asks for the password and does not proceed from there

**To Reproduce**

Steps for the devs to reproduce the behavior:
1. I have no idea

**Expected behavior**

The menu should open

**Troubleshooting**

I tried fetching the latest version from the repository

Did you read the docs: [Yes]

**Screenshots**

![image](https://user-images.githubusercontent.com/21367039/114083137-89deb880-98a6-11eb-97c6-9aa67e79052c.png)

**Comment by Nimdy** [comment]
you need to use a sudo account to open the menu.

sudo ./menu.sh
