### ISSUE TITLE
Second Server [FEATURE]

### ISSUE THREAD

**Issue by Btaito** [Nimdy/Dedicated_Valheim_Server_Script#253]
Would it be possible to add a way to fire up a second server instance on different ports? I'm currently using this program and I get how to do it on the normal start up config file but thought it would be cool if there was a way to incorporate it into the Njord Menu features. I already have my primary world on Njord and figured it would be easier to run two instances vs me spinning up a second Linux VM.

**Comment by Nimdy** [comment]
noted. I have something already but I dont want folks messing up their installs...

Maybe you can test it for me. :)

**Comment by Btaito** [comment]
Yeah if you want to let me know. I just racked in an old 64 core opteron
dell r815 in my home cabinet so I have plenty of cores left to run a test
server.

**Comment by Nimdy** [comment]
this request will be filled on the next update

**Comment by slotvana** [comment]
any idea on timeline for this?

**Comment by Nimdy** [comment]
Its ready in the beta branch...

We are just testing it... Trying to make it easy for others who have not used the njordmenu in the past.

Some variables need to be auto populated during initial launch.

Almost there.

https://github.com/Nimdy/Dedicated_Valheim_Server_Script/blob/beta/njordmenu.sh

**Comment by Nimdy** [comment]
Sorry it took so long, I had to finish the function that would allow for easy upgrading from the advancemenu to the njordmenu.  

This will allow you to run multiple valheim servers on one server. (As long as you have enough system resources)

The script will update the following:

1. Rebuilds file pathing for Valheim
2. Rebuilds the configuration start files
3. Rebuilds the system service files
4. Reset permissions

I need to test V+ and Bep installs next and I need to tweak one function action.

I think I will have it ready for testing within two days.

**Comment by Nimdy** [comment]
![image](https://user-images.githubusercontent.com/16698453/119361785-51573a80-bcac-11eb-8988-0672a9d81efd.png)

Two instances running on the same server :)

**Comment by RonKrc** [comment]
Will we get the update soon? :-)

**Comment by Nimdy** [comment]
> Will we get the update soon? :-)

I need testers... to test upgrading their menus... from advancemenu to njordmenu

That would help.

I plan on releasing it this week....

I was gone for four days... so I am home now and I will do more testing but it works for me and I have tried on a ton of different installs.

Let me know.

**Comment by RonKrc** [comment]
> I need testers... to test upgrading their menus... from advancemenu to njordmenu

I want to test :-)

**Comment by KingHuslter** [comment]
Would love to be a tester if possible

**Comment by Nimdy** [comment]
Officially released! Update your menu system and use the ./njordmenu.sh option
