### ISSUE TITLE
[TECH SUPPORT}worlds.txt: No such file or directory

### ISSUE THREAD

**Issue by OhNoItSJoe** [Nimdy/Dedicated_Valheim_Server_Script#254]
- **Hosted Status:** [Local Home Server]
- **Valheim Game Version:** [?]
- **Type of Request:** [other]

**Describe your issue**

Hello, I just tried to start the advancedmenu.sh after a while. It started and I was ready to update my Valheim server.
So I started the script but now it is saying the following:
./advancemenu.sh: line 68: /home/steam/worlds.txt: No such file or directory
./advancemenu.sh: line 582: syntax error near unexpected token `then'
./advancemenu.sh: line 582: `    else command -v yum >/dev/null; then'

I never had a worlds.txt file before.. what am I doing wrong?

**To Reproduce**

**Expected behavior**

**Troubleshooting**

**Screenshots**

**Comment by Nimdy** [comment]
that was a mistake... not sure why main had the beta update... just update the menu and try again....

Sorry about that.

**Comment by OhNoItSJoe** [comment]
No problem, mistakes happen and your script saved me so much time already!
