### ISSUE TITLE
[FEATURE]Begin using SCRIPT with Steam Installed server on Ubuntu Studio 20.10 Plasma

### ISSUE THREAD

**Issue by CoolGames** [Nimdy/Dedicated_Valheim_Server_Script#257]
**Is your feature request related to a problem? Please describe.**
I have been running a dedicated private server for many family members for months.
It was install by selecting TOOLS in STEAM Library.
I then change to the directory and start with provided script

> $ cd /home/user/.local/share/Steam/steamapps/common/Valheim\ dedicated\ server/
> $ ./start_server_xterm.sh

**Describe the solution you'd like**
It would require a new script to migrate from non-service manually started standard STEAM TOOLS version 
with filename that would contain the SPACE character to check configuration and status then add service and maintain with menu.sh or advancedmenu.sh

**Describe alternatives you've considered**
Moving, modifying or duplicating dedicated server that would break using STEAM TOOLS in the future.
This is not going to be easy to maintain using existing Valheim or future resources as they may change significantly after their return to normal or larger effort [starting May 2021](https://store.steampowered.com/news/app/892970).

**Additional context**
The STEAM TOOLS does not see the server running using the documented method of running from STEAM provided script when installed on Ubuntu Studio 20.10 Plasma distribution.

![Valheim - Dedicated Server - including STEAM - Screenshot_2021-04-26_10-42-08](https://user-images.githubusercontent.com/149711/116102337-a2a7e600-a67c-11eb-8382-7ffa21ed87b8.png)

**Comment by Nimdy** [comment]
hmmmm...

My servers show up with no issue... 

Also servers showing up is still hit or miss... this is an official issue and a still on going issue with ARK Servers... 

I will poke around... but my servers will pop on the list and come off... but IDK....

**Comment by Nimdy** [comment]
Also, how are you using the script?
start_server_xterm.sh just calls xterm -hold -e ./start_server.sh, so you dont close the process.

The start_valheim.sh script we built, used a system service and is ran by steam.  This service is then always running in the background. 

The xterm, is not needed here...

**Comment by LordDumoss** [comment]
I believe you might have posted this feature request on the wrong site.
Did you want to add this to the official Steam Client?
If so that that site is ... https://developer.valvesoftware.com/wiki/Steam

... Or you can use this system to manage Valheim servers using their other system Steam Command (Line) 
... ... https://developer.valvesoftware.com/wiki/SteamCMD

PS. This system will install both the Steam client and SteamCMD for you too.

**Comment by CoolGames** [comment]
Even though closed I want to clarify my system implementation.
I found and followed those instructions which has no system service implemented. 
`.local/share/Steam/steamapps/common/Valheim dedicated server/Valheim Dedicated Server Manual.pdf`

I do see the redundancy in using the xterm so I will avoid using in future.
Also, I will be trying the SteamCMD so thanks for the heads up.
