### ISSUE TITLE
[FEATURE] Monitor Server status - status page

### ISSUE THREAD

**Issue by leafshore** [Nimdy/Dedicated_Valheim_Server_Script#262]
I would like a way to monitor the Valheim server. See that it's alive and how many players there are.
Something like on this one: https://github.com/lloesche/valheim-server-docker#status-web-server

**Comment by Nimdy** [comment]
You can install cockpit and do this. 

https://github.com/Nimdy/Dedicated_Valheim_Server_Script/wiki/How-to-secure-your-Dedicated-Valheim-Server-(Ubuntu)-and-maximize-your-Administrative-experience-with-the-Advance-Menu-System

I have a walkthrough at the bottom of this page.

We are also adding a real GUI just for Valheim Servers.
