### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by skynett81** [Nimdy/Dedicated_Valheim_Server_Script#263]
I want an automatic backup-solution that you can set to take backups of the game-server(s) .
it can also take backups before updates from Valheim and Valheim +  services .

**Comment by Nimdy** [comment]
this is outlined here

https://github.com/Nimdy/Dedicated_Valheim_Server_Script/wiki/How-to-set-automatic-backups-for-Valheim-Server-World-Data-in-Ubuntu
