### ISSUE TITLE
sleep 10 during backup doesn't do what's attempting to do.

### ISSUE THREAD

**Issue by unixtreme** [Nimdy/Dedicated_Valheim_Server_Script#268]
https://github.com/Nimdy/Dedicated_Valheim_Server_Script/blob/8a5e24d88a0c21ab1a032167399ceddf288d08d4/menu.sh#L470

There's a sleep 10 to "wait for RAM to flush", on a server that isn't busy it will be enough time, on a server that is being hammered it may not be. I'd suggest using the Linux command meant for flushing: [sync](https://linux.die.net/man/8/sync).

**Comment by Nimdy** [comment]
@unixtreme new release. Ready for input so we can make it better. Thank you again!

**Comment by unixtreme** [comment]
> @unixtreme new release. Ready for input so we can make it better. Thank you again!

Hey Sorry, where can I find your Discord? I was pretty tied up and got distracted.
