### ISSUE TITLE
Could I add the player limit?

### ISSUE THREAD

**Issue by duncan1126** [Nimdy/Dedicated_Valheim_Server_Script#269]
I want to change the player limit from 10 to 20?
cloud you help me?
thanks

=====

P. S . I change the /home/steam/valheimserver/valheim_server_Data/Managed/assembly_valheim.dll
serverPlayerLimit +10

When I start server: the coding will be reset (by steam (user))

**Comment by Nimdy** [comment]
you need to use doorstop for this.  This is why people use Bepinex for modding Unity games. 

Plus this mod is already found on Nexus or if you use ValheimPlus

TL:DR- You need to use mods

**Comment by duncan1126** [comment]
Could I add the mod in my server?

**Comment by Nimdy** [comment]
yes. You will need to use the advance menu

and go to the bepenix option and install bepenix and then enable bepenix and then download the mods.... but you should watch some videos on adding mods to Valheim... because they need to be installed on the server and on your game client.

**Comment by duncan1126** [comment]
Thanks for your reply,
I'll try it.
