### ISSUE TITLE
Server build show 'no data'  ,ERROR! Failed to install app '896660' (Disk write failure)'

### ISSUE THREAD

**Issue by duncan1126** [Nimdy/Dedicated_Valheim_Server_Script#270]
Thank you for your video, I learned more.
I follow the step install valheim server in my machine,
after produce and the "server build" show no data
![image](https://user-images.githubusercontent.com/81570676/121292667-ebf68100-c91c-11eb-8392-4abd4fa6fcb7.png)

Then, I do the update "4",
the steam says' I follow the step do, then steam say  ERROR! Failed to install app '896660' (Disk write failure)'
![image](https://user-images.githubusercontent.com/81570676/121292968-6a532300-c91d-11eb-8cde-8e7e9ba9e084.png)
the build still no data.

I checked the disk space it's enough
![image](https://user-images.githubusercontent.com/81570676/121292963-658e6f00-c91d-11eb-80c9-844807b59d38.png)

BTW, I tried the method on my local linux and gcp VM there are same problem.

Please help me... thank you!

**Comment by Nimdy** [comment]
This issue was corrected and I am glad you figured it out!
