### ISSUE TITLE
[BUG] Unable to install steamcmd on fresh install

### ISSUE THREAD

**Issue by mtderryberry** [Nimdy/Dedicated_Valheim_Server_Script#276]
**Describe the bug**
While attempting to follow the README and setup guide, I'm hitting an error after trying to install the Valheim Server. This is on an EC2 instance with AWS. After inputting all of my information, I get the following error:

```
Downloading and installing Steam and Official Valheim Server
/home/steam/steamcmd/steamcmd.sh: /home/steam/steamcmd/linux32/steamcmd: /lib/ld-linux.so.2: bad ELF interpreter: No such file or directory
```

Full log output from the install client is below:
```
Installing steamcmd and libsdl2
oops7
mkdir: cannot create directory ‘steamcmd’: File exists
./njordmenu.sh: line 779: [: -fe: unary operator expected
--2021-06-29 03:27:03--  https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
Resolving steamcdn-a.akamaihd.net (steamcdn-a.akamaihd.net)... 23.12.144.72, 23.12.144.71, 23.12.144.67, ...
Connecting to steamcdn-a.akamaihd.net (steamcdn-a.akamaihd.net)|23.12.144.72|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2428561 (2.3M) [application/octet-stream]
Saving to: ‘steamcmd_linux.tar.gz.1’

100%[===================================================================================================================================================================================================>] 2,428,561   --.-K/s   in 0.04s

2021-06-29 03:27:03 (51.6 MB/s) - ‘steamcmd_linux.tar.gz.1’ saved [2428561/2428561]

Done
Building symbolic link for steamcmd
ln: failed to create symbolic link ‘/home/steam/steamcmd/linux32/steamcmd’: File exists
Done
Downloading and installing Steam and Official Valheim Server
/home/steam/steamcmd/steamcmd.sh: /home/steam/steamcmd/linux32/steamcmd: /lib/ld-linux.so.2: bad ELF interpreter: No such file or directory
Done
Setting steam permissions
Done
Done
Deleting old configuration if file exist
Building Valheim start_valheim server configuration
./njordmenu.sh: line 478: /home/steam/valheimserver/Nalpigo/start_valheim_Nalpigo.sh: No such file or directory
Done
Deleting old check log script if exist
Setting execute permissions on start_valheim.sh
chmod: cannot access ‘/home/steam/valheimserver/Nalpigo/start_valheim_Nalpigo.sh’: No such file or directory
Done
Deleting old configuration if file exist
Building systemctl instructions for Valheim
Done
Setting steam account permissions to /home/steam/*
Done
Reloading daemons and spawning Necks
Done
By Thors Hammer we are Starting the Valheim Server
Job for valheimserver_Nalpigo.service failed because the control process exited with error code. See "systemctl status valheimserver_Nalpigo.service" and "journalctl -xe" for details.
Done
Enabling Valheim Server on start or after reboots
Done
Check server status by typing systemctl status valheimserver.service
```

I'm not sure what went wrong, this is a fresh EC2 instance so nothing else is setup yet aside from the steps I followed from the README. 

**Expected behavior**
Server is installed and starts up

**Hosting Company (please complete the following information):**
 - Cloud Provider: AWS

**Additional context**

**Comment by Nimdy** [comment]
What OS install is this on?

Is this a fresh install or on top of another server install?

**Comment by mtderryberry** [comment]
The instance is running Amazon Linux 2, it is a t3.medium host. This is a fresh install, I spun up the server, pulled down this code, and ran the install

**Comment by Nimdy** [comment]
Did you run as root?

Fresh installs never have any issues, unless its not running Ubuntu 18 or 20.

The error:
mkdir: cannot create directory ‘steamcmd’: File exists

thats very strange... it was almost as if steamcmd was already installed but this is a fresh install, so that should have happened.

I believe Amazon Linux 2 is running a CENTOS or Red Hat install and not Ubuntu.

This is most likely the issue. If you spin up just a Ubuntu 20 install, you will not have this issue.  There are most steps you need to do but the new njordmenu should also install on any flavor of Linux now... unless there is a official repo issue with steamcmd.


 @JamieeLee thoughts on this homies
