### ISSUE TITLE
[FEATURE] -logfile parameter for launch options

### ISSUE THREAD

**Issue by urbels** [Nimdy/Dedicated_Valheim_Server_Script#279]
**Is your feature request related to a problem? Please describe.**
Any change -logfile launch parameter could be implemented? Or some option to to edit launch parameters and add it.

**Describe the solution you'd like**
-logfile outputs server log to file path.

**Comment by Nimdy** [comment]
Sure thing, we can add it to next release and have the logfile default set to dump into /home/steam/valheimserver/WORLDNAME/logs

Thank you.

You could add it manually but I am not sure without testing if the sed functions for pulling variables will get jacked up.

**Comment by urbels** [comment]
I will wait for next release no problem! Thank you!

**Comment by Nimdy** [comment]
feature added. Thank you, please update your menu system.
