### ISSUE TITLE
Fresh Installation error

### ISSUE THREAD

**Issue by NeoDragonXDA** [Nimdy/Dedicated_Valheim_Server_Script#282]
Installation errors on Debian 11

E: Package 'lib32gcc1' has no installation candidate

---- Dependency check fails because the package has been renamed as per Debian 11 to  lib32gcc1-s1

E: Unable to locate package isof

---- I guess this is a type and you're checking for dependency of lsof package, not isof ?

Error: 'multiverse' invalid

---- No multiverse in Debian

Thanks!

**Comment by Nimdy** [comment]
Jump into Discord. There are answer there.  Basically you have to good how to get steamcmd to work and install correctly for Debian 11... its not tricky just a few extra steps.  After that you will be fine.
