### ISSUE TITLE
Ubuntu 22.04 LTS Support

### ISSUE THREAD

**Issue by Taxick** [Nimdy/Dedicated_Valheim_Server_Script#287]
Hi.

I have used this script long time, and I love it.

But after I got a new server that runs Ubuntu 22.04 this script make some errors then I run the install script the first time.

```
here's is one of the errors i got:

Install Git, Locate, Curl, Unzip and Net-Tools
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package lib32gcc1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  lib32gcc-s1

E: Package 'lib32gcc1' has no installation candidate
E: Unable to locate package libsdl2-2.0-0:i386
E: Couldn't find any package by glob 'libsdl2-2.0-0'
E: Unable to locate package isof
Done
```

Will the script still work after this error? Or can it be fixed some way??

**Comment by Nimdy** [comment]
Happy to help you out! Happy gaming!

**Comment by ejtejada** [comment]
Hello, firstly, I understand that your problem was resolved. HOWEVER, simply saying you got the fix on Discord, a service which cannot be web-crawled, leaves those of us in the future trying to run this on Ubuntu 22.04 or later in the dark. 
Please reopen this issue and explain the fix?

**Comment by Taxick** [comment]
@ejtejada - I did not use the script anymore. And I can't remember the fix anymore! - Sorry!
