### ISSUE TITLE
Add AWS EC2 Firewall Rule Procedure to Initial Instructions.

### ISSUE THREAD

**Issue by BigWincy** [Nimdy/Dedicated_Valheim_Server_Script#29]
I used AWS, instead of Azure.

On my first go, I added IP to IP security on the EC2 instance (usually a good practice). I also didn't open the correct ports. Needless to say, Steam and Valheim never saw the server. I purged the first instance and tried again.

When creating the EC2 instance, you need to add a rule opening up ports 2456->2458. I left the IP as 0.0.0.0. Meaning, I don't think the server will work if you choose the default settings (usually, only port 22 is open). Go through the full set up process and you will see the port configuration. This should be done for the EC2 and the OS (already in the instructions).

I don't think the full procedures for AWS need to be spelled out, but there probably should be an "honorable mention" added in the instructions.

Also, I used the Steam->View->Servers->Favorites feature to test the server. It was very easy to refresh and "track" my success this way, instead of using the client. I also created a favorite for each of the 3 possible ports to see which one would ping back. It only takes a few seconds to update a successful Steam-to-server connection.

**Comment by futurejohn** [comment]
I managed to get my EC2 server to show up in the Favorites list, but I had to use the value in Public IPv4 address rather than the inet value in ifconfig.

I'm not able to connect to it in the game itself, though.

Any tips on debugging what the issue could be?
