### ISSUE TITLE
[BUG] World folder wrong path

### ISSUE THREAD

**Issue by Terule** [Nimdy/Dedicated_Valheim_Server_Script#293]
**Describe the bug**
The function get_worldseed() and display_world_data_folder() are broken because they reference the path 
```${worldpath}/${worldname}/worlds/${worldname}.fwl```
```$worldpath/$worldname/worlds```

but as you can see in the screenshot the correct path is "worlds_local"

Post your logs:
cat /var/log/syslog* | grep Info

**To Reproduce**

**Expected behavior**
See the seed or folder info

**Screenshots**
![Screenshot 2022-12-04 084421](https://user-images.githubusercontent.com/20166561/205488495-eb49373e-7ac1-4212-86bf-65b5331ee24e.png)

**Hosting Company (please complete the following information):**
 - Cloud Provider: Digital Ocean

**Additional context**

**Comment by Nimdy** [comment]
checking

**Comment by Nimdy** [comment]
Fixed

![image](https://user-images.githubusercontent.com/16698453/206052034-2dea8a02-3583-4c5c-bef8-8041238aa95c.png)
