### ISSUE TITLE
[FEATURE] See active players in njordmenu

### ISSUE THREAD

**Issue by apertureless** [Nimdy/Dedicated_Valheim_Server_Script#295]
**Is your feature request related to a problem? Please describe.**
I am managing a valheim server and would find it very useful to see if there are any active players on the server before I shutdown for backup.

**Describe the solution you'd like**
Showing if / how many active players are on the server currently

**Describe alternatives you've considered**
Alternatives would either be to login to valheim to check or add the server to steam favorite servers, where you see how many players are connected.

**Comment by apertureless** [comment]
Thanks! I will look into it.  I was trying to get the connected players via `netstat` but it was not very reliable.

**Comment by Nimdy** [comment]
> **Is your feature request related to a problem? Please describe.** I am managing a valheim server and would find it very useful to see if there are any active players on the server before I shutdown for backup.
> 
> **Describe the solution you'd like** Showing if / how many active players are on the server currently
> 
> **Describe alternatives you've considered** Alternatives would either be to login to valheim to check or add the server to steam favorite servers, where you see how many players are connected.

![image](https://user-images.githubusercontent.com/16698453/233879000-b59832a5-42a0-425f-843b-8df370108a05.png)

**Comment by Nimdy** [comment]
Added this. Thank you
