### ISSUE TITLE
Wiki: Can't open Migrate World Data from Server to Server

### ISSUE THREAD

**Issue by Pendora2017** [Nimdy/Dedicated_Valheim_Server_Script#30]
By clicking the link in the Wiki >Error: You do not have permission to update this wiki

I don't want to update - i wan't to migrate my World Data ^^

**Comment by devdavi** [comment]
That page got setup before it was actually created. We'll take care of that shortly, sorry it's been a flurry of activity.

You can reference this explanation by @Nimdy [here](https://github.com/Nimdy/Dedicated_Valheim_Server_Script/issues/5#issuecomment-778589560)

**Comment by Nimdy** [comment]
https://github.com/Nimdy/Dedicated_Valheim_Server_Script/wiki/Migrate-Valheim-Map-Data-from-server-to-server

should work...

**Comment by devdavi** [comment]
Updated the link on the main wiki page to the actual migration page.
