### ISSUE TITLE
Install SDL to surpress SDL errors 

### ISSUE THREAD

**Issue by joaoanes** [Nimdy/Dedicated_Valheim_Server_Script#31]
Hi, thanks for building this!

I suggest you install `libsdl2-2.0-0 libsdl2-2.0-0:i386` alongside `steamcmd` in the [build script](https://github.com/Nimdy/Dedicated_Valheim_Server_Script/blob/main/build_dedicated_valheim_server.sh#L45). Doing so [surpresses](https://github.com/ValveSoftware/steam-for-linux/issues/7036) `Failed to init SDL priority manager: SDL not found` warnings that I find in the `steamcmd` and the valheim server's logs under Ubuntu 18.04. I can push a PR if you want so you can test it!

Thanks again! 🙇

**Comment by elmat0** [comment]
In your experience does this boost server performance etc. in any way?

**Comment by Nimdy** [comment]
@joaoanes 

All about. I will be able to test at home later as well but feel free.

Thank you.

@elmat0 

Since the last update, my CPU and RAM cut in half and I have 10/10 people on my server 24/7

**Comment by joaoanes** [comment]
> In your experience does this boost server performance etc. in any way?

I couldn't run a proper benchmark, but I feel like it cuts the valheim server start-up time by a considerable amount (the server seems to be up in like half the time), and it also might make steamcmd faster but that I don't feel so sure about!
