### ISSUE TITLE
[BUG] BepInEx Redirect Error

### ISSUE THREAD

**Issue by dannzen** [Nimdy/Dedicated_Valheim_Server_Script#311]
**Describe the bug**
Trying to install BepInEx Integration results in a 404 not found zip file, cause they removed the subdomain structure

New Filepath, without Subdomains:
https://thunderstore.io/package/download/denikson/BepInExPack_Valheim/5.4.2202/

Old Filepath, with Subdomains
https://valheim.thunderstore.io/package/download/denikson/BepInExPack_Valheim/5.4.2202/

Hardcoded Path in File
https://github.com/Nimdy/Dedicated_Valheim_Server_Script/blob/9384a46d486c2375f64e9f38178bb7b0e0939618/njordmenu.sh#L2594-L2598

**To Reproduce**
1. Go to 'Menu 21) BepInEx Only Menu Options'
2 Go to 'Menu 1) Install BepInEx Mods'

**Expected behavior**
Installing BepInEx

**Screenshots**
![image](https://github.com/Nimdy/Dedicated_Valheim_Server_Script/assets/11268594/acd10c8c-ce5d-4cd4-9710-5b379828f218)

**Comment by vincebel7** [comment]
If anyone wants this fixed quickly, I saw this fork with the fix: https://github.com/talissondc/Dedicated_Valheim_Server_Script

Looks like Nimdy's Discord server link is broken so can't alert him about it :(

**Comment by Nimdy** [comment]
> If anyone wants this fixed quickly and doesn't want to just make the change themselves, I saw this fork with the fix: https://github.com/talissondc/Dedicated_Valheim_Server_Script
> 
> Looks like Nimdy's Discord server link is broken as well

Updated the redirect, thank you
