### ISSUE TITLE
How to properly remove?

### ISSUE THREAD

**Issue by SpoinkyNL** [Nimdy/Dedicated_Valheim_Server_Script#34]
Hi,

Games come and go 😃
Whats the best approach for when to eventually remove the server?

**Comment by devdavi** [comment]
In terms of removing Valheim from the server or shutting down the server on your host?

**Comment by karljakober** [comment]
the script is well documented. just go from bottom to top and do the opposite steps

**Comment by Nimdy** [comment]
blow away your server... never install a game on your production boxes... but all you have to do is remove the valheimserver.services.... and then delete the game.

Sure Steam has tons of tuts on this already.

**Comment by SpoinkyNL** [comment]
Hey, yeah just removing it.


I saw the scropt is well documented but since it's a script focused on automating as much of the process as possible I figured a simple way to reverse the process might be desirable too

Just a suggestion, nothing more :)
