### ISSUE TITLE
How to handle Server Updates

### ISSUE THREAD

**Issue by CBusse** [Nimdy/Dedicated_Valheim_Server_Script#37]
Hi,

your build script works fairly well for me, but I have one question:

How will we handle Server Updates?

I had never used steamcmd before and am new to it fyi.

So my guess is I would have to stop the service and do some action as the steam user?

Or is simply stopping and starting  enough to get an updated dedicated server without loosing the world data?

**Comment by gkuehn001** [comment]
Have you already read the section [How to Update Your Valheim Server](https://github.com/Nimdy/Dedicated_Valheim_Server_Script/wiki/How-to-Update-Your-Valheim-Server) ?

**Comment by CBusse** [comment]
probably not, checking now, thx.

**Comment by Nimdy** [comment]
> Hi,
> 
> your build script works fairly well for me, but I have one question:
> 
> How will we handle Server Updates?
> 
> I had never used steamcmd before and am new to it fyi.
> 
> So my guess is I would have to stop the service and do some action as the steam user?
> 
> Or is simply stopping and starting enough to get an updated dedicated server without loosing the world data?

Correct everything is in the WIKI.  

@gkuehn001 thank you for responding and helping out!
