### ISSUE TITLE
my server not showing & can't connect

### ISSUE THREAD

**Issue by PercyGFX** [Nimdy/Dedicated_Valheim_Server_Script#39]
i manage to set up a server on a aws t2.micro (only 2 of us going to play on it ). 

but server is not showing on game OR i can't use connect command to log in the server

here is a screnshot of server status
![Annotation 2021-02-19 173049](https://user-images.githubusercontent.com/32939626/108502132-520cb900-72d8-11eb-8227-8d51e5e387c0.png)

and i have opened ports from security groups 

![image](https://user-images.githubusercontent.com/32939626/108502228-7cf70d00-72d8-11eb-90cc-fbb549d58302.png)

**Comment by Nimdy** [comment]
I am going to roll the dice here and say... not enough system resources.  Every time we have helped somebody with a similar issue, it came down to this.

t2-micros are only 1CPU 1GB RAM

You need 2 CPUs and 4GB RAM (2CPU and 2GB RAM might work)

Boost up the resources to 2CPUs and try again.

**Comment by PercyGFX** [comment]
thanks for the reply. i will try with google servers
