### ISSUE TITLE
Keeps Crashing

### ISSUE THREAD

**Issue by JZwanepoel1996XD** [Nimdy/Dedicated_Valheim_Server_Script#44]
Hi, 
I'm running a local Linux server 
With 4 Cores 4 threads, 8 Gb ram. 

The service keeps shutting down,
It stays online for under 1 min then goes down automatically or crashes
<a href="https://ibb.co/3SCGVTn"><img src="https://i.ibb.co/3SCGVTn/awe.png" alt="awe" border="0"></a>

**Comment by JZwanepoel1996XD** [comment]
When it goes online for a couple of seconds
<a href="https://ibb.co/YRhZYpy"><img src="https://i.ibb.co/YRhZYpy/Online.png" alt="Online" border="0"></a>

**Comment by Nimdy** [comment]
there is something else going on... not related to the script.

Did you read through the wiki?
https://github.com/Nimdy/Dedicated_Valheim_Server_Script/wiki/Top-10-Reason-your-Server-is-not-working-and-how-to-fix

**Comment by gkuehn001** [comment]
Maybe you can find any useful information about what's happening in the full service journal just before the shutdown:

`sudo journalctl -u valheimserver.service`

or with 

`sudo journalctl -u valheimserver.service -e`

to automatically scroll to the end of the log

or maybe something here?
`/home/steam/.steam/logs/stderr.txt`

**Comment by JZwanepoel1996XD** [comment]
HI, @Nimdy I will take a look at the wiki and see if I can find a way to fix this,
Thanks, @GKUEHN01 I will take a look at the logs and see if I can find the issue.

**Comment by Nimdy** [comment]
Something isn't correct. Pm on discord your config file

**Comment by Nimdy** [comment]
I think everything is good on your side now...

If not post again in Discord.

A lot of issue we are helping people with is way beyond this script.. Sysadmin and Networking configurations and tweaks seem to be the main issues for users on cloud services and ESXI/PROXMOX...

We will add more lessons learned to the WIKI.
