### ISSUE TITLE
Update server script without losing world data?

### ISSUE THREAD

**Issue by angryfoxnoises** [Nimdy/Dedicated_Valheim_Server_Script#49]
Greetings!

I know updating the game version has been addressed, but how do I update the script itself? I built my Valheim server using the day zero script, and now I’m wanting all the cool updates that have come out since this project has taken off.

I’ve considered resetting my VM instance, but I want to save the world file that I currently have. Obviously I’m open to less extreme ideas as well. In any case my friends and I literally have a few hundred person hours on our world already, and they would hate me if I lost all that work.

Thanks!

**Comment by Nimdy** [comment]
My new menu has a built in menu function for backing up.

Backup away!!!

**Comment by angryfoxnoises** [comment]
See that's the thing. I don't have the version of the script with the menu and I was wondering how to get that.

For reference, this is what I see when I SSH into Google cloud.

[
![Screenshot (3)](https://user-images.githubusercontent.com/79210086/108604554-3d7dfe80-7374-11eb-8764-51c118bf51ad.png)
](url)

**Comment by Nimdy** [comment]
switch user to root
cd /opt
git clone https://github.com/Nimdy/Dedicated_Valheim_Server_Script
cd Dedicate Valheim Server Scipt
chown steam:steam menu.sh
sudo ./menu

Try that

**Comment by angryfoxnoises** [comment]
Thank you! I just had to leave for work, but I'll update with results at around 1am US eastern time.

**Comment by Nimdy** [comment]
![menu start](https://user-images.githubusercontent.com/16698453/108605138-953b5a80-73b2-11eb-9d0c-c46c951fb035.gif)

**Comment by angryfoxnoises** [comment]
That didn't seem to work. I got it to work the first time I tried it, but then the next time I SSH'd into my server, I lost the menu. Now I can't seem to consistently clone into the provided link. Here's the error I'm getting. Any advice? 

![Screenshot (5)](https://user-images.githubusercontent.com/79210086/108619314-84f2a200-73e9-11eb-8444-8a265ecb0b31.png)

**Comment by emilime93** [comment]
It says that the directory already exists.
You could probably just do the following:
However, beware that this will remove the changes you made to the script file (with the passwords, world-names etc.)
`
$ cd Dedicated_Valheim_Server_Script
$ git reset .
$ git pull origin main
`

**Comment by emilime93** [comment]
An alternative would be to clone the new version to a separate repository, and just copy the menu file from there. I don't know if it relies on other changes made to the repository, and if it will work or not.
```bash
git clone https://github.com/Nimdy/Dedicated_Valheim_Server_Script tmp
cp tmp/menu.sh Dedicated_Valheim_Server_Script/
```
And then follow Nimdy's previous steps

**Comment by angryfoxnoises** [comment]
Thank you for your patience, I'm giving myself a crash course in Ubuntu so I can do this more independently in the future. I ended up doing the latter and that worked perfectly. And now I have a copy of the repository on my server just in case. Thanks!

**Comment by Nimdy** [comment]
The new menu system will create a file for reviewing later, if you use it for installing. 

Just remember to chmod +x menu.sh

and when the menu has new updates... you can update it from within the menu system

**Comment by max-png** [comment]
Thanks very much for this, was going to manually backup the world. Does the copy of the world end up in the same location as the copied one?

**Comment by Nimdy** [comment]
Yes and a copy is dumped into /home/steam/backups

**Comment by dreamalligator** [comment]
Didn't make a new issue, because I think kindof touched on in issues like this, but I can if you all wish.. I was wondering if there is a way to know when something crucial gets added to the master branch. Should I make sure to update on every major semver change? Thanks!

**Comment by Nimdy** [comment]
I am not a very good programmer... I am guess the github function check that is using curl would also need to check a special tag that I build in the future and then based on that... update.

I am open to helpers :)
