### ISSUE TITLE
Uploading and Using an existing world?

### ISSUE THREAD

**Issue by polishdude20** [Nimdy/Dedicated_Valheim_Server_Script#5]
How would I go about running the server using a world I've uploaded that already exists?

**Comment by Nimdy** [comment]
This is not a issue with the script but here is the solution to what you are seeking.

SFTP into your Server as steam (recommend using WINSCP)


Copy your saved world information

/home/steam/Downloads/whateverworldname.db
/home/steam/Downloads/whateverworldname.fwl

ls /home/steam/.config/unity3d/IronGate/Valheim/worlds

cp /home/steam/.config/unity3d/IronGate/Valheim/worlds/whateverworldname.db /home/steam/.config/unity3d/IronGate/Valheim/worlds/whateverworldname.dbOLDBAD
cp /home/steam/.config/unity3d/IronGate/Valheim/worlds/whateverworldname.fwl /home/steam/.config/unity3d/IronGate/Valheim/worlds/whateverworldname.fwlOLDBAD

rm /home/steam/.config/unity3d/IronGate/Valheim/worlds/whateverworldname.db
rm /home/steam/.config/unity3d/IronGate/Valheim/worlds/whateverworldname.fwl

cp /home/steam/Downloads/whateverworldname.db /home/steam/.config/unity3d/IronGate/Valheim/worlds/
cp /home/steam/Downloads/whateverworldname.fwl /home/steam/.config/unity3d/IronGate/Valheim/worlds/

Make sure the configuration file reflects the worldname correctly

/home/steam/valheimserver/start_valheim.sh

./valheim_server.x86_64 -name steam -port 2456 -nographics -batchmode -world whateverworldname -password YourPass

start the server
