### ISSUE TITLE
Can't set god mode?

### ISSUE THREAD

**Issue by leokwsw** [Nimdy/Dedicated_Valheim_Server_Script#50]
I followed your tutorial to setup a Valheim server on Google Cloud.

But how can I set server owner to me ? 
I want to get got mode and spawn some object

**Comment by BigWincy** [comment]
God mode or Imacheater commands are only for single player games. I've read it in a few locations, but cant find anything official at the moment. Here's IGN... 

https://www.ign.com/wikis/valheim/Cheats_and_Codes_List_(Console_Commands)

> Before you can continue delving into the world of cheats, you will need to ensure that cheats are activated by typing "imacheater". However, it is worth noting that cheats can only be used in singleplayer and will not work on multiplayer servers.
