### ISSUE TITLE
Graceful shutdown and start up of droplet?

### ISSUE THREAD

**Issue by VictorioBerra** [Nimdy/Dedicated_Valheim_Server_Script#53]
If I shut down my droplet to save money when not in use, does issuing a normal shutdown command through the DO portal/panel gracefully shut down the VM? Or is there risk of data loss?

**Comment by andrew-canning** [comment]
The DO console first tries to issue a graceful shutdown command to the VM.  Then does a force shutdown of the VM if that doesn't work.  If your systemctl process is properly set up (which the script does for you) you should be ok.  I've been turning off and on Valheim servers in AWS with success (ubuntu 20.04).
