### ISSUE TITLE
Transferring Files from existing server onto AWS

### ISSUE THREAD

**Issue by Llum97** [Nimdy/Dedicated_Valheim_Server_Script#54]
My friend has a dedicated server running locally on his computer, but we would like to transfer those files onto AWS. I have an AWS server running and copied the world files (.db/.fwl) files over, but every time I run the server and log on, it will create a new world.
As an added note, the server that my friend has on locally and the one I'm running on AWS has 2 different names, so i tried renaming everything to the same name, but that did not work.

**Comment by Nimdy** [comment]
I believed we help you in discord.  

Always check pathing
always check permissions
always make sure the valheim server server is stopped before moving into the /worlds/ director
always make sure the valheim start configuration file... matches the new world .db and .fwl files.
