### ISSUE TITLE
Process for updating an existing Valheim service?

### ISSUE THREAD

**Issue by andrew-canning** [Nimdy/Dedicated_Valheim_Server_Script#55]
I was just wondering if there was an established process for updating a Valheim server that has be set up using this repo.  Not sure what are the correct steps to make sure the existing world state is saved but keeping the server binary up to date with Iron Gate releases.

**Comment by Nimdy** [comment]
https://github.com/Nimdy/Dedicated_Valheim_Server_Script/wiki/How-to-Update-Your-Valheim-Server

Also if you never used my script or anything.  The start_server.sh does it on restart just like my script.
