### ISSUE TITLE
Could I change the file assembly_valheim.dll?

### ISSUE THREAD

**Issue by dkalke** [Nimdy/Dedicated_Valheim_Server_Script#59]
file-path: /home/steam/valheimserver/valheim_server_Data/Managed/assembly_valheim.dll
I modify the file to get more upload/download speed. [refer to Reddit](https://www.reddit.com/r/valheim/comments/lp9lmt/server_fix_for_multiplayer_lagdesync_dummy_proof/)

When the server start/restart, the file will be changed to the original version.

Have any solution to solve this problem?

**Comment by Nimdy** [comment]
cannot answer you on the DLL file... Not sure about that. That seems to be modding.

Also, yes any changes to the base file systems are validated after each server launch. You would need to edit the valheim_start.sh file and remove validation.  I am not sure on the other options you would need to complete but the modding pages found within github can help you.
