### ISSUE TITLE
Server not showing up in list of servers

### ISSUE THREAD

**Issue by polishdude20** [Nimdy/Dedicated_Valheim_Server_Script#6]
I've gone through all of the steps successfully and have the dedicated server service running and active.  The problem is I can't see my server at all in the game.

**Comment by polishdude20** [comment]
Oh I see from the youtube video if it doesn't show up do this:

In launch options in steam type "+connect yourServerIP:2456"

**Comment by Nimdy** [comment]
There are issues with steam and IronGate server listing... nothing to do with the script. Glad it all worked out for you. :)

**Comment by DorWixDevalore** [comment]
Not everyone watch the video.
If you can add this method to the main readme file will be great (would have same me few hours)

**Comment by Nimdy** [comment]
> Not everyone watch the video.
> If you can add this method to the main readme file will be great (would have same me few hours)

I believe I had it here: https://github.com/Nimdy/Dedicated_Valheim_Server_Script/wiki/Top-10-Reason-your-Server-is-not-working-and-how-to-fix

I have added the link the front page. Thank you
