### ISSUE TITLE
menu.sh option 1 fails

### ISSUE THREAD

**Issue by huntertj** [Nimdy/Dedicated_Valheim_Server_Script#63]
https://github.com/Nimdy/Dedicated_Valheim_Server_Script/blob/b3ea860fc340dfa5bef8ca4bbbccd7aecff12baa/menu.sh#L112

```
Choose an option: 1
Saved working directory and index state WIP on main: b3ea860 Update menu.sh
fatal: Invalid object name 'https'.
fatal: Invalid object name 'origin/https'.
Updating your branch https://github.com/Nimdy/Dedicated_Valheim_Server_Script/tree/main
Already up to date.
Resetting permissions on menu.sh
Restarting menu system
```
I think the fix is to change `BRANCH=main` if I'm understanding the process

Also would be nice to `git stash apply` if an update was found, or alternatively store the "4 things you need to change" in a config file

**Comment by Nimdy** [comment]
thanks, I will look into it... I couldnt find a example... so I am just trying something...

It does update though...for fresh downloads... 

I will try! Thanks!

**Comment by Nimdy** [comment]
Also the new Menu system stores the configs for ref... its in /home/steam/server_info.txt

**Comment by warsix4** [comment]
I am still getting this issue when I try to update the script. How can I update without losing anything?

**Comment by Nimdy** [comment]
what issue?

Also you will not lose anything when the menu system.  Valheim operates in its own area.  The Menu system is just a outside puppet master.

**Comment by warsix4** [comment]
The menu was giving me the same error as the OP had shown. I have since updated it by cloning the git to a new directory and simply overwriting the old menu.sh with the new one. It does work this way now. Thanks!

**Comment by Nimdy** [comment]
oh nice! I need to figure out a way to have it delete everything and reapply...

**Comment by Nimdy** [comment]
updated! thank you! Everything works like a champ now on this function!
