### ISSUE TITLE
Adding ValheimPlus to this

### ISSUE THREAD

**Issue by sherang** [Nimdy/Dedicated_Valheim_Server_Script#65]
In the wiki it points to ValheimPlus installation. I followed Ubuntu steps to launch the server and everything is working. Do I just have to rename start_server_bepinex.sh to start_valheim.sh and reboot server for this to work?

**Comment by Nimdy** [comment]
no. I have not added it yet this is a future addition.

I do not mind helping others with unstable early access game but adding mod tech support... not a joyful outlook.

Once I have my script 100% and the game is closer to stable and the mods are stable... I will be adding V+ or whoever is the most stable
