### ISSUE TITLE
Service file location wrong

### ISSUE THREAD

**Issue by QuadeHale** [Nimdy/Dedicated_Valheim_Server_Script#7]
`/etc/systemd/system` is the location for root-level systemd scripts.
Your service file should live in `/lib/systemd/system` instead.

**Comment by Nimdy** [comment]
Thanks. I will think it over.

**Comment by Nimdy** [comment]
I am still leaning to leaving it as is because not a lot of user know how to use Linux. For the Linux masters... I can understand the view but do you think this is best so user created account can executed the services without root?

Thoughts?

**Comment by Nimdy** [comment]
Going to close.  If there is a strong stance to set this differently, then I am all for it but I feel this is opinionated (nothing wrong with that btw).

**Comment by QuadeHale** [comment]
You've got it backwards. Only root level service files should go in
/etc/systemd/system. User level (general) service files should go in
/lib/systemd/system.

Files in /etc/ with the same name override ones in /lib/. When making a new
one, always put it in /lib/.

Only the location changes, permissions don't.

**Comment by Nimdy** [comment]
Thanks QuadeHale... I will switch them around. :) Sometimes we forget some basics :P
