### ISSUE TITLE
Requirements for Steam user password do not match passwd requirements.

### ISSUE THREAD

**Issue by MrDetonia** [Nimdy/Dedicated_Valheim_Server_Script#78]
The script requires passwords to have passwords of 5 characters or more; with at least one number, one uppercase letter, and one lowercase letter. Symbols are not allowed.

This does not match the password requirements usually enforced by the passwd command from shadow-utils:

> Then, the password is tested for complexity. As a general
       guideline, passwords should consist of 6 to 8 characters
       including one or more characters from each of the following sets:
>       •   lower case alphabetics
>       •   digits 0 thru 9
>       •   punctuation marks

_- from [passwd(1) manpage](https://man7.org/linux/man-pages/man1/passwd.1.html)_

The script could instead pass off complexity checking to the passwd command, rather than enforcing its own requirements which may not always be compatible with the version of passwd installed on the system.

**Comment by Nimdy** [comment]
I understand your point edit the script and make push if you like.

This was not designed for advance Linux users. This was designed to open the world to those that might be afraid of Linux.  The menu system is like a gateway for this targeted group.  They learn the basic and they have a menu to help them with basic functions.

Feel free to add to the script with this in mind.

Ensure the variables stick and not break the script on passing the information. 

Looking forward to seeing what you come up with. :)
