### ISSUE TITLE
Going to kill off the build_dedicated_valheim_server.sh now that menu.sh is stable

### ISSUE THREAD

**Issue by Nimdy** [Nimdy/Dedicated_Valheim_Server_Script#79]
I am going to remove the build_dedicated_valheim_server.sh script.

80% of the problems are still coming people misconfiguring the variables.

**Comment by stephenclau** [comment]
lemme get it from your repo before you deprecate it altogether. I got an idea to use it with a dockerfile to spawn containers! thanks in advance!

**Comment by Nimdy** [comment]
no worries. I am going to just have people use the menu system now...
