### ISSUE TITLE
Set world file path?

### ISSUE THREAD

**Issue by teelau** [Nimdy/Dedicated_Valheim_Server_Script#8]
Thanks for this script! got it up and running, but i'm trying to migrate a previously created world to run when the server is up. Is there a way to modify the script to change the world file path?

**Comment by Nimdy** [comment]
Not a script issue.

Here is the answer to your question.

Yes you can modify it and change anything you wish.  However, the script is built to respect the default pathing that Iron Gate devs have set.

Changing this might calls issues later on.

To move your data:

https://github.com/Nimdy/Dedicated_Valheim_Server_Script/wiki/Moving-map-data-from-internal-server-to-external-cloud-server
