### ISSUE TITLE
[Feature Request] Cron-jobs 

### ISSUE THREAD

**Issue by VP-EN** [Nimdy/Dedicated_Valheim_Server_Script#81]
Hey Nimdy

It would be very nice to have some sort of easy setup of cronjobs. Especially for things like the `Backup Server` and `Check and Apply Valheim Server Update` features 👍

**Comment by NickDJM** [comment]
Seconded!

I currently have a couple cronjobs running for hourly/daily/weekly backups, but it would be super cool to have the option to set these up through the menu interface.

Hourly might be overkill for the built-in options, but daily or semi-daily would be good for people to have.

**Comment by VP-EN** [comment]
Maybe at some very odd-hours as well, like 04:00AM. I don't think I have anyone on my server at that time of day atleast 😄

**Comment by pygnode** [comment]
Upvote! Trying to pipe answers into the interactive script may also need some tweaking:

`sudo echo 2 | sudo ./menu.sh` leads me to:

```
Choose an option: Wrong option.
./menu.sh: line 1182: WrongCommand: command not found
./menu.sh: line 1188: syntax error near unexpected token `done'
./menu.sh: line 1188: `done'
```

**Comment by madamsmall** [comment]
Yes please. Auto update and restart every 24 hours would be amazing while they’re pushing so many fixes instead of waking up every morning to texts from my players asking to restart it manually.

**Comment by lightkiwi** [comment]
Hi,
I made my own script for backup (from menu.sh) and run it every night with cron.
But I thought about something : what if you could run the menu directly in your cron

I added this at the end of menu.sh insted of "menu" (I made a fork, but I'm not used to github and I'm not sure how 
```
# Call the menu function or the shortcut called in arg
if [ $# = 0 ]; then
    menu
else
    case "$1" in
    start)
        start_valheim_server
        ;;
    stop)
        stop_valheim_server
        ;;
    restart)
        restart_valheim_server
        ;;
    update)
        check_apply_server_updates_beta
        ;;
    backup)
        backup_world_data
        ;;
    status)
        display_valheim_server_status
        ;;
    *)
        menu
        ;;
    esac
fi
```
Then you jsut have to use `menu.sh backup` to backup the server.
And in order to use it in cron, maybe add functions that don't ask for confirmation ?

**Comment by Nimdy** [comment]
Adding this today or tomorrow... but this weekend for sure
