### ISSUE TITLE
Backup Filename Error

### ISSUE THREAD

**Issue by W1ndst0rm** [Nimdy/Dedicated_Valheim_Server_Script#82]
The filename generated in the backup script may contain a space depending on the users locale settings, which tar interprets as a second file. This shows up as an error in the console. A backup is still created, just not with the expected filename.

When the backup script gets the current data time and stores it in a variable `TODAY="$(date +%Y-%m-%d-%X)` the %X format string uses the locale's time representation. I'm running Ubuntu 20.04.2 LTS with the locale set to en_US.UTF-8 and this returns `2021-02-26-12:08:56 PM`.  Changing this to `TODAY="$(date +%Y-%m-%d-%T)` will use 24 hour time `2021-02-26-12:16:24`.

**Comment by Nimdy** [comment]
fixed thank you!
