### ISSUE TITLE
Cant update to 0.146.11

### ISSUE THREAD

**Issue by CriminalOwl** [Nimdy/Dedicated_Valheim_Server_Script#84]
If i use the Menu script i cant update to the newest version. it says it is up to date.

**Comment by Nimdy** [comment]
restart services... it will work... Tweaking the update script... it seems to be cached... and that doesnt make sense... I had to restart my services...

**Comment by Nimdy** [comment]
looking into it

**Comment by Nimdy** [comment]
update the menu.

Placed the old updater in there it will work, until we figure out the new way.
