### ISSUE TITLE
Server Updates and Backups

### ISSUE THREAD

**Issue by TheDakk** [Nimdy/Dedicated_Valheim_Server_Script#9]
Not an issue, but have two questions: 

1) How are server updates handled when new releases come out? Does it auto update with SteamCMD? 

2) Is there a proper way to backup the DB files? or auto backup?

**Comment by Nimdy** [comment]
No a script related issue.

1. Every time you stop, start and the server reboots, the /etc/systemd/system/valheimserver.service file that was created checks for official Valheim server updates.  If updates are found, the server will automatically update it and restart.

2. As of right now... not really.  You can create your own cron job to set a copy backup yourself.

Let me just spit one out for you real quick:
1. Make backup startup files
```sh
sudo touch /usr/local/bin/valheimbackup && sudo chmod +x /usr/local/bin/valheimbackup
```
2. Make backup directory in steam home folder called backups
```sh
sudo mkdir /home/steam/backups
```
3. Edit backup file for Valheim
```sh
vi /usr/local/bin/valheimbackup
```

```sh
#!/bin/bash

## Get the current date as variable.
TODAY="$(date +%Y-%m-%d)"

## Clean up files older than 2 weeks. Create a new backup.
find /var/Valheim-backup/ -mtime +14 -type f -delete

## Tar Section. Create a backup file, with the current date in its name.
## Add -h to convert the symbolic links into a regular files.
## Backup some system files, also the entire `/home` directory, etc.
## --exclude some directories, for example the the browser's cache, `.bash_history`, etc.
tar zcvf "/home/steam/backups/valheim-backup-$TODAY.tgz" /home/steam/.config/unity3d/IronGate/Valheim/worlds/* 
chown steam:steam valheim-backup-$TODAY.tgz
```

Now you should be able to execute the command valheimbackup and it will do a manual backup.

Now to set automatically.... which I dont know if this is bad or good but whatever... I would shutdown the server with nobody on it and then do the backup... I am unclear on the amount of possible data loss... or corrupter evil demons that can happen to server world data.... still testing... and playing around

Make a crontab: 

This is for nightly backups, if you want to increase or decrease time, research making crontabs....


```sh
 15 1 * * * /usr/local/bin/valheimbackup > /var/log/valheimbackup-cron.log 2>&1
```



I am in my Discord if you need anything...

**Comment by Nimdy** [comment]
Updated:
Please validate the script.... THIS IS A BETA!



1. Make backup startup files
```sh
sudo touch /usr/local/bin/valheimbackup && sudo chmod +x /usr/local/bin/valheimbackup
```
2. Make backup directory in steam home folder called backups
```sh
sudo mkdir /home/steam/backups
```
3. Edit backup file for Valheim
```sh
vi /usr/local/bin/valheimbackup
```

```sh
#!/bin/bash

## Get the current date as variable.
TODAY="$(date +%Y-%m-%d)"

## Clean up files older than 2 weeks. Create a new backup.
find /home/steam/backups/ -mtime +14 -type f -delete

## Tar Section. Create a backup file, with the current date in its name.
## Add -h to convert the symbolic links into a regular files.
## Backup some system files, also the entire `/home` directory, etc.
## --exclude some directories, for example the the browser's cache, `.bash_history`, etc.
tar zcvf "/home/steam/backups/valheim-backup-$TODAY.tgz" /home/steam/.config/unity3d/IronGate/Valheim/worlds/* 
chown steam:steam valheim-backup-$TODAY.tgz
```

Conduct manual backup

type ```sh
valheimbackup
```

Now to set automatically.... which I dont know if this is bad or good but whatever... I would shutdown the server with nobody on it and then do the backup... I am unclear on the amount of possible data loss... or corrupter evil demons that can happen to server world data.... still testing... and playing around

Make a crontab: 

This is for nightly backups, if you want to increase or decrease time, research making crontabs....


```sh
 15 1 * * * /usr/local/bin/valheimbackup > /var/log/valheimbackup-cron.log 2>&1
```



I am in my Discord if you need anything...
