### ISSUE TITLE
Server never saves

### ISSUE THREAD

**Issue by tmoerkerken** [Nimdy/Dedicated_Valheim_Server_Script#90]
I'm successfully running the server on a VM. I was working on a backup strategy but after inspection of the "last modified date" (on linux using `ll`), my world .db and .fwl are never updated: the date says that the last write was done 4 days ago. Even though I used the f5 > save option today. I'm very worried that when I stop the server, that my progress is lost. Note that the server actually is up to date when I join, its state is seemingly just not stored in the .db and .fwl files. Is this expected behavior?

**Comment by Nimdy** [comment]
not a script issue. tech support request.

You would need to check the permissions within your VM.

Not sure what you mean by VM... Workstation, VirtualBox, ESXi, Proxmox.... Cloud hosted(which company)

**Comment by tmoerkerken** [comment]
I'm running it on a Digital Ocean droplet.
Not sure about the permissions, seems to be read/write?
`779148     4 drwxr-xr-x 2 root  root      4096 Feb 26 17:21 .
779145     4 drwxr-xr-x 3 steam steam     4096 Feb 26 18:35 ..
779176 23040 -rw-r--r-- 1 root  root  23589878 Feb 23 09:59 Meadows.db
779179     4 -rw-r--r-- 1 root  root        43 Feb 23 09:59 Meadows.fwl`

**Comment by Nimdy** [comment]
Needs to be steam.

It's in the walk through

**Comment by tmoerkerken** [comment]
Thanks, missed it. I applied the steam user and group to the world folder with `chown` and things started working.
