### ISSUE TITLE
High Availability/Docker Support

### ISSUE THREAD

**Issue by desponda** [Nimdy/Dedicated_Valheim_Server_Script#95]
I run a few kubernetes clusters for hosting various infrastructures projects, it would be great to have valheim server dockerized so it can be run on kubernetes with a file system set up for high availability if/when the server gets restarted.

**Comment by Nimdy** [comment]
already in progress by another team member...

**Comment by desponda** [comment]
@Nimdy is there an issue or PR for that?

**Comment by Nimdy** [comment]
There is no issue at all. Not sure on release date... I would have ask and see where things are.  I am just trying to get this bad boy completed.

You could pull  from history and grab the build script and use that if you wanted to make one :)

**Comment by desponda** [comment]
@Nimdy yeah i was starting the work on that last night but also wanted to make sure there wasn't already some ongoing work on it for collaboration, def good to get it completed, its an awesome project so far and I have my server up and running with this!

**Comment by Nimdy** [comment]
oh by all means.  Make one.. We are just adding a bunch of functions and other items. 

The more people making something the better.  I know there seems to be a lot of docker build already on github.... 

but you might be able to make the best one :)

**Comment by Nimdy** [comment]
closing.. Feel free to update, when you have something and if you want to drop it here or on your own repo. I can link it if you like
