### ISSUE TITLE
Can't run the server with Valheim Plus

### ISSUE THREAD

**Issue by rako233** [Nimdy/Dedicated_Valheim_Server_Script#96]
After installation, everything is fine, but a feature of Valheim Plus is missing, which is configuring a higher data rate. So I installed Valheim Plus but I've got a message in the Valheim Plus client the server is outdated. I would be great to get a choice between a Valheim/Valheim Plus installation.

**Comment by rako233** [comment]
Since I've installed Valheim more than one time, it would be great when the process of installation is reading the necessary data from a file, when such a file exist. Excluded should be the password for the steam user. Is the steam user existing, no password isn't necessary anyway.

**Comment by Nimdy** [comment]
I am not providing support for V+ or any mods until the game is ready or we are 100% with complete with the menu system and future GUI project.  Mods will come later. 
If you want mods, you have to install them yourself.  I do not have the bandwidth to help folks with sysadmin/networking/security and other issues folks have their installs, if I am also providing help with mods.
