### ISSUE TITLE
Port to Connect to

### ISSUE THREAD

**Issue by BillChirico** [Nimdy/Dedicated_Valheim_Server_Script#99]
Hello,

I'm using Digital Ocean and whenever I click connect it does nothing in-game. Any ideas?

Thanks,
- Bill

**Comment by Nimdy** [comment]
Did you read the wiki?

Did you follow all the steps?

https://github.com/Nimdy/Dedicated_Valheim_Server_Script/wiki

**Comment by BillChirico** [comment]
@Nimdy Resolved, it was an ISP issue thank you!
